In [1]:
from LoopStructural.supports.structured_tetra import TetMesh
from LoopStructural.cython.dsi_helper import tetra_neighbours
import numpy as np

In [8]:
mesh = TetMesh(nsteps=[2,2,2])
mesh.nodes

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 1., 0.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [1., 1., 1.]])

In [2]:
mesh = TetMesh(nsteps=[3,2,2])
neighbours = np.sort(mesh.get_neighbours())[:,::-1]
elements = mesh.get_elements()
neighbours2 = np.zeros((elements.shape[0],4)).astype('int64')
neighbours2[:] = -1
tetra_neighbours(elements,neighbours2)
neighbours2 = np.sort(neighbours2)[:,::-1]
print(neighbours)
print(neighbours2)
for i in range(neighbours2.shape[0]):
    for j in range(4):
        if neighbours[i,j] not in neighbours2[i,:]:
            print(i,i % 5, (i // 5) % 2, mesh.global_index_to_cell_index(i//5)[0],\
                  mesh.global_index_to_cell_index(i//5)[1],\
                  mesh.global_index_to_cell_index(i//5)[2],neighbours[i,:],neighbours2[i,:])

[[ 4  3  2  1]
 [ 0 -1 -1 -1]
 [ 0 -1 -1 -1]
 [ 0 -1 -1 -1]
 [ 8  0 -1 -1]
 [ 9  8  7  6]
 [ 5 -1 -1 -1]
 [ 5 -1 -1 -1]
 [ 5 -1 -1 -1]
 [ 5  3 -1 -1]]
[[ 4  3  2  1]
 [ 9  0 -1 -1]
 [ 0 -1 -1 -1]
 [ 0 -1 -1 -1]
 [ 6  0 -1 -1]
 [ 9  8  7  6]
 [ 5  4 -1 -1]
 [ 5 -1 -1 -1]
 [ 5 -1 -1 -1]
 [ 5  1 -1 -1]]
4 4 0 [0] [0] [0] [ 8  0 -1 -1] [ 6  0 -1 -1]
9 4 1 [1] [0] [0] [ 5  3 -1 -1] [ 5  1 -1 -1]


In [3]:
mesh = TetMesh(nsteps=[2,3,2])
neighbours = np.sort(mesh.get_neighbours())[:,::-1]
elements = mesh.get_elements()
neighbours2 = np.zeros((elements.shape[0],4)).astype('int64')
neighbours2[:] = -1
tetra_neighbours(elements,neighbours2)
neighbours2 = np.sort(neighbours2)[:,::-1]
for i in range(neighbours2.shape[0]):
    for j in range(4):
        if neighbours[i,j] not in neighbours2[i,:]:
            print(i,i % 5, (i // 5) % 2, mesh.global_index_to_cell_index(i//5)[0],\
                  mesh.global_index_to_cell_index(i//5)[1],\
                  mesh.global_index_to_cell_index(i//5)[2],neighbours[i,:],neighbours2[i,:])

1 1 0 [0] [0] [0] [ 9  0 -1 -1] [ 8  0 -1 -1]
3 3 0 [0] [0] [0] [ 7  0 -1 -1] [ 6  0 -1 -1]
4 4 0 [0] [0] [0] [ 6  0 -1 -1] [ 0 -1 -1 -1]
6 1 1 [0] [1] [0] [ 5  4 -1 -1] [ 5  3 -1 -1]
8 3 1 [0] [1] [0] [ 5  2 -1 -1] [ 5  1 -1 -1]
9 4 1 [0] [1] [0] [ 5  1 -1 -1] [ 5 -1 -1 -1]


In [6]:
mesh = TetMesh(nsteps=[2,2,3])
neighbours = np.sort(mesh.get_neighbours())[:,::-1]
elements = mesh.get_elements()
neighbours2 = np.zeros((elements.shape[0],4)).astype('int64')
neighbours2[:] = -1
tetra_neighbours(elements,neighbours2)
neighbours2 = np.sort(neighbours2)[:,::-1]

for i in range(neighbours2.shape[0]):
    for j in range(4):
        if neighbours[i,j] not in neighbours2[i,:]:
            print(i,i % 5, (i // 5) % 2, mesh.global_index_to_cell_index(i//5)[0],\
                  mesh.global_index_to_cell_index(i//5)[1],\
                  mesh.global_index_to_cell_index(i//5)[2],neighbours[i,:],neighbours2[i,:])

1 1 0 [0] [0] [0] [ 8  0 -1 -1] [ 0 -1 -1 -1]
6 1 1 [0] [0] [1] [ 5  3 -1 -1] [ 5 -1 -1 -1]


In [5]:
ic = 24 // 5
it = 24 % 5
print(mesh.global_index_to_cell_index(ic),it)

(array([1], dtype=int32), array([0], dtype=int32), array([1], dtype=int32)) 4
