In [1]:
%load_ext cython
import matplotlib.pyplot as plt
import meshpy.tet
import numpy as np
#%load_ext snakeviz

In [45]:
11 // 10

1

In [136]:
%%cython -a
import numpy as np
def build_aabb(int nx, int ny, int nz, long [:,:] tetra, double [:,:] nodes, long [:,:] aabb, double [:] step):
    cdef int i, ntetra, j, ix, iy, iz
    cdef double [:,:] bb = np.zeros((2,3))
#     cdef double [:] maxs = np.zeros(3)
    cdef double [:,:] points = np.zeros((4,3))
    ntetra = tetra.shape[0]
    # create a mask for extracting corners from 
    cdef long [:,:] corners = np.array([[0, 1, 0, 0, 1, 0, 1, 1],
                                        [0, 0, 1, 0, 0, 1, 1, 1],
                                        [0, 0, 0, 1, 1, 1, 0, 1]]).astype(int)
    
    cdef long [:] tetra_count= np.zeros(nx*ny*nz).astype(int)
    for i in range(ntetra):
        # copy points into tmp array
        for k in range(4):
            for l in range(3):
                points[k,l] = nodes[tetra[i,k],l]
        for l in range(3):
            bb[0,l] = np.min(points[:,l])#,axis=0)
            bb[1,l] = np.max(points[:,l])#,axis=0)
#             print(bb[0,l],bb[1,l])
        # check which corners of bounding box are inside a cell 
        for j in range(8):
            ix = int(bb[corners[0,j],0] // step[0]) 
            iy = int(bb[corners[1,j],1] // step[1])
            iz = int(bb[corners[2,j],2] // step[2]) 
            aabb[ix+nx*iy+nx*ny*iz,tetra_count[ix+nx*iy+nx*ny*iz]] = i
            tetra_count[ix+nx*iy+nx*ny*iz]+=1


    return

In [137]:
%%cython -a
cdef stp(double [:] v1, double [:] v2, double [:] v3):
    cdef double [3] c

    s = 0.
    c[0] = v1[1]*v2[2]-v1[2]*v2[1]
    c[1] = v1[2]*v2[0]-v1[0]*v2[2]
    c[2] = v1[0]*v2[1]-v1[1]*v2[0]
    s = c[0]*v3[0] + c[1]*v3[1] + c[2]*v3[2]
    return s
import numpy as np
def find_tetras(double [:,:] nodes, long [:,:] tetras, long [:,:] aabbindx, double [:,:] pos, 
               double [:,:] bcs, long [:] tetra_index):
    cdef int npts = pos.shape[0]
    cdef int ntetra 
    cdef int i,j,k, l
    cdef double [3] vap, vbp, vab, vac, vad, vbc, vbd
    cdef double va, vb, vc, vd, v
    cdef double [4] c
    for i in range(npts):
        ntetra = len(aabbindx[i,:])
        for j in range(ntetra):
            # aabbindx should be ordered so, if we get to -1 then skip
            print(aabbindx[i,j])
            if aabbindx[i,j] < 0:
                break
            for k in range(3):
                vap[k] = pos[i,k] - nodes[tetras[aabbindx[i,j],0],k]
                vbp[k] = pos[i,k] - nodes[tetras[aabbindx[i,j],1],k]
                
                vab[k] = nodes[tetras[aabbindx[i,j],1],k] - nodes[tetras[aabbindx[i,j],0],k]
                vac[k] = nodes[tetras[aabbindx[i,j],2],k] - nodes[tetras[aabbindx[i,j],0],k]
                vad[k] = nodes[tetras[aabbindx[i,j],3],k] - nodes[tetras[aabbindx[i,j],0],k]
                vbc[k] = nodes[tetras[aabbindx[i,j],2],k] - nodes[tetras[aabbindx[i,j],1],k]
                vbd[k] = nodes[tetras[aabbindx[i,j],3],k] - nodes[tetras[aabbindx[i,j],1],k]
                
            va = 0
            vb = 0
            vc = 0
            vd = 0
            v = 0
            # calculate scalar triple product as each bc coordinate
            # if any coordinte is 0 then this tetra is not the right one so keep looking
            v = stp(vac,vad,vab)
            v /= 6.
            if v <= 0:
                print('v < 0')
                continue
            va = stp(vbd,vbc,vbp)
            va /= 6.
            va /= v
            if va < 0:
                print('va < 0')
                continue
            vb = stp(vac,vad,vap)
            vb /= 6.
            vb /= v
            if vb < 0:
                print('vb <0')
                continue
            vc = stp(vad,vab,vap)
            vc /= 6.
            vc /= v
            if vc < 0:
                print('vc < 0')
                continue
            vd = stp(vab,vac,vap)
            vd /= 6.
            vd /= v
            if vd < 0:
                print('vd < 0')
                continue

            # all three coordinates should be > 0
            tetra_index[i] = aabbindx[i,j]
            bcs[i,0] = va
            bcs[i,1] = vb
            bcs[i,2] = vc
            bcs[i,3] = vd
            

                
#                 vab = points[:, :, 1, :] - points[:, :, 0, :]
#                 vac = points[:, :, 2, :] - points[:, :, 0, :]
#                 vad = points[:, :, 3, :] - points[:, :, 0, :]
#                 vbc = points[:, :, 2, :] - points[:, :, 1, :]
#                 vbd = points[:, :, 3, :] - points[:, :, 1, :]
#             vap = pos[i,:] - 
#         vap = pos[i,:] - nodes[] 
#         vap = pos[:,None,:] - points[:, :, 0, :]
#         vbp = pos[:,None,:] - points[:, :, 1, :]
#         # vcp = p - points[:, 2, :]
#         # vdp = p - points[:, 3, :]
#         vab = points[:, :, 1, :] - points[:, :, 0, :]
#         vac = points[:, :, 2, :] - points[:, :, 0, :]
#         vad = points[:, :, 3, :] - points[:, :, 0, :]
#         vbc = points[:, :, 2, :] - points[:, :, 1, :]
#         vbd = points[:, :, 3, :] - points[:, :, 1, :]
        
#         va = np.einsum('ikj, iklj->ikl', vbp, np.cross(vbd, vbc, axisa=2, axisb=2)) / 6.
#         vb = np.einsum('ikj, iklj->ikl', vap, np.cross(vac, vad, axisa=2, axisb=2)) / 6.
#         vc = np.einsum('ikj, iklj->ikl', vap, np.cross(vad, vab, axisa=2, axisb=2)) / 6.
#         vd = np.einsum('ikj, iklj->ikl', vap, np.cross(vab, vac, axisa=2, axisb=2)) / 6.
#         v = np.einsum('ikj, iklj->ikl', vab, np.cross(vac, vad, axisa=2, axisb=2)) / 6.
#         c = np.zeros((va.shape[0],va.shape[1],4))

In [153]:
class TetMesh2:
    def __init__(self,origin,maximum,nodes,tetra,neighbours,nx=2,ny=2,nz=2):
        self.origin = np.array(origin)
        self.maximum = np.array(maximum)
        self.nodes = nodes
        self.tetra = tetra
        self.ntetra = tetra.shape[0]

        self.neighbours = neighbours
        self.step = (self.maximum-self.origin)/(np.array([nx,ny,nz]))
        print(self.step)
        self.aabb = np.zeros(((nx+1)*(ny+1)*(nz+1),self.ntetra)).astype(int)

        self.nx = nx 
        self.nz = nz 
        self.ny = ny 
        
#         nx -= 1
#         ny -=1 
#         nz-=1
        self.aabb[:] = -1

        self._build_aabb()
        self.corners = np.array([[0, 1, 0, 0, 1, 0, 1, 1],
                                      [0, 0, 1, 0, 0, 1, 1, 1],
                                      [0, 0, 0, 1, 1, 1, 0, 1]]).astype(int)
    def _build_aabb(self):
        build_aabb(self.nx+1,self.ny+1,self.nz+1,self.tetra,self.nodes-0.5*self.step,self.aabb,self.step)
        bb = np.zeros((3,2))
        idx = np.arange(0,self.aabb.shape[0])
        xi,yi,zi = self.global_aabb_index_to_local(idx[np.all(self.aabb == -1,axis=1)])
        bb = np.zeros((3,2))
        for i in range(xi.shape[0]):
            bb[0,0] = xi[i]*self.step[0] - self.step[0]*0.5
            bb[0,1] = (xi[i]+1)*self.step[0] - self.step[0]*0.5

            bb[1,0] = yi[i]*self.step[1] - self.step[1]*0.5
            bb[1,1] = (yi[i]+1)*self.step[1] - self.step[1]*0.5

            bb[2,0] = zi[i]*self.step[2] - self.step[2]*0.5
            bb[2,1] = (zi[i]+1)*self.step[2] - self.step[2]*0.5

            corners = np.array([[0, 1, 0, 0, 1, 0, 1, 1],
                                                [0, 0, 1, 0, 0, 1, 1, 1],
                                                [0, 0, 0, 1, 1, 1, 0, 1]]).astype(int)
            corner_loc = np.zeros((8,3))
            corner_loc[:,0] = bb[0,corners[0,:]]#bb[corners]
            corner_loc[:,1] = bb[1,corners[1,:]]
            corner_loc[:,2] = bb[2,corners[2,:]]
            for j, t in enumerate(self.tetra):
                points = self.nodes[t] - self.step*0.5
                vap = corner_loc[:,None,:] - points[None,  0, :]
                vbp = corner_loc[:,None,:] - points[None, 1, :]
        #         # vcp = p - points[:, 2, :]
        #         # vdp = p - points[:, 3, :]
                vab = points[None, 1, :] - points[None, 0, :]
                vac = points[None, 2, :] - points[None, 0, :]
                vad = points[None, 3, :] - points[None, 0, :]
                vbc = points[None, 2, :] - points[None, 1, :]
                vbd = points[None, 3, :] - points[None, 1, :]

                va = np.sum(vbp * np.cross(vbd, vbc, axisa=1, axisb=1)) / 6.
                vb = np.sum(vap * np.cross(vac, vad, axisa=1, axisb=1)) / 6.
                vc = np.sum(vap * np.cross(vad, vab, axisa=1, axisb=1)) / 6.
                vd = np.sum(vap * np.cross(vab, vac, axisa=1, axisb=1)) / 6.
                v = np.sum(vab * np.cross(vac, vad, axisa=1, axisb=1)) / 6.

                c = np.zeros((4,8))
                c[0,:] = va / v
                c[1,:] = vb / v
                c[2,:] = vc / v
                c[3,:] = vd / v
#                 print(np.all(c>0,axis=0))
                if np.any(np.all(c>0,axis=0)):
#                     print('All points inside a tetra')
#                     print(self.aabb[xi[i]+yi[i]*self.nx+zi[i]*self.nx*self.ny,0])
                    self.aabb[xi[i]+yi[i]*self.nx+zi[i]*self.nx*self.ny,0] = j
#                     print(self.aabb[xi[i]+yi[i]*self.nx+zi[i]*self.nx*self.ny,0])
                    break
#                 if j == self.
        #         print(mesh2.calc_bary(corner_loc,t))

        #         points = mesh.nodes[t]
        #         print(points)
                if j == len(self.tetra)-1:
                    print(corner_loc)
                    print('Couldnt find any tetra')
    
    
        # now sort
    def get_tetra2(self,pos):
        pos = np.array(pos) - self.step*.5
        tetras = np.zeros(pos.shape[0]).astype(int)
        bcs = np.zeros((pos.shape[0],4))
        for i in range(pos.shape[0]):
            aabbidx = self.pos_to_aabb_index(pos)
            cells = self.aabb[aabbidx[i],:]
            cells=cells[cells>=0]
            npts = len(cells)
            points = self.nodes[self.tetra[cells]]
            vap = pos[i,:] - points[:, 0, :]
            vbp = pos[i,:] - points[:, 1, :]
            # vcp = p - points[:, 2, :]
            # vdp = p - points[:, 3, :]
            vab = points[:, 1, :] - points[:, 0, :]
            vac = points[:, 2, :] - points[:, 0, :]
            vad = points[:, 3, :] - points[:, 0, :]
            vbc = points[:, 2, :] - points[:, 1, :]
            vbd = points[:, 3, :] - points[:, 1, :]

            va = np.sum(vbp * np.cross(vbd, vbc, axisa=1, axisb=1), axis=1) / 6.
            vb = np.sum(vap * np.cross(vac, vad, axisa=1, axisb=1), axis=1) / 6.
            vc = np.sum(vap * np.cross(vad, vab, axisa=1, axisb=1), axis=1) / 6.
            vd = np.sum(vap * np.cross(vab, vac, axisa=1, axisb=1), axis=1) / 6.
            v = np.sum(vab * np.cross(vac, vad, axisa=1, axisb=1), axis=1) / 6.
            
            c = np.zeros((4, npts))
            c[0, :] = va / v
            c[1, :] = vb / v
            c[2, :] = vc / v
            c[3, :] = vd / v
#             print(c)
            tetras[i] = cells[np.all(c>0,axis=0)]
            #             print(c)
            bcs[i,:] = c[:,np.all(c>0,axis=0)].T
            
        return tetras,bcs
    
    def calc_bary(self,pos,tetra):
            points = self.nodes[self.tetra[tetra]]
            vap = pos - points[:, 0, :]
            vbp = pos - points[:, 1, :]
            # vcp = p - points[:, 2, :]
            # vdp = p - points[:, 3, :]
            vab = points[:, 1, :] - points[:, 0, :]
            vac = points[:, 2, :] - points[:, 0, :]
            vad = points[:, 3, :] - points[:, 0, :]
            vbc = points[:, 2, :] - points[:, 1, :]
            vbd = points[:, 3, :] - points[:, 1, :]

            va = np.sum(vbp * np.cross(vbd, vbc, axisa=1, axisb=1), axis=1) / 6.
            vb = np.sum(vap * np.cross(vac, vad, axisa=1, axisb=1), axis=1) / 6.
            vc = np.sum(vap * np.cross(vad, vab, axisa=1, axisb=1), axis=1) / 6.
            vd = np.sum(vap * np.cross(vab, vac, axisa=1, axisb=1), axis=1) / 6.
            v = np.sum(vab * np.cross(vac, vad, axisa=1, axisb=1), axis=1) / 6.
            
            c = np.zeros((4))
            c[0] = va / v
            c[1] = vb / v
            c[2] = vc / v
            c[3] = vd / v
            
            return c
    def get_tetrac(self,pos):
        aabbidx = self.pos_to_aabb_index(pos)
        # get the tetras for each aabb cell where our points are -1 are tetras which 
        # aren't seen in the cell'
        tetra_index = np.zeros(pos.shape[0]).astype(int)
        tetra_index[:] = -1
        bcs = np.zeros((pos.shape[0],4))
        cells = self.aabb[aabbidx,:]
        find_tetras(self.nodes, self.tetra, cells, pos,bcs,tetra_index)
        return tetra_index, bcs
    def get_tetra(self,pos):
        pos = np.array(pos)
        
        # create containers to store the results (tetra and the bc for each point)
        tetras = np.zeros(pos.shape[0]).astype(int)
        tetras[:] = -1
        bcs = np.zeros((pos.shape[0],4))
        
        # find the aabb cells for each point
        aabbidx = self.pos_to_aabb_index(pos)
        # get the tetras for each aabb cell where our points are -1 are tetras which 
        # aren't seen in the cell
        cells = self.aabb[aabbidx,:]
        
        # create a in array the same shape as cells array
        pos_idx = np.tile(np.arange(cells.shape[0]).T,(cells.shape[1],1)).astype(int).T
    
        # slice the pos and cells arrays for only the tetras that are inside out aabb cells
        # this will create a flat array of points and tetras
        pos2 = pos[pos_idx[cells>0]]
        cells2 = cells[cells>0]
        npts = pos2.shape[0]
        # now calculate the barycentric coordinates for all of these points
        points = self.nodes[self.tetra[cells2]]
        vap = pos2 - points[:, 0, :]
        vbp = pos2 - points[:, 1, :]
        # vcp = p - points[:, 2, :]
        # vdp = p - points[:, 3, :]
        vab = points[:, 1, :] - points[:, 0, :]
        vac = points[:, 2, :] - points[:, 0, :]
        vad = points[:, 3, :] - points[:, 0, :]
        vbc = points[:, 2, :] - points[:, 1, :]
        vbd = points[:, 3, :] - points[:, 1, :]

        va = np.sum(vbp * np.cross(vbd, vbc, axisa=1, axisb=1), axis=1) / 6.
        vb = np.sum(vap * np.cross(vac, vad, axisa=1, axisb=1), axis=1) / 6.
        vc = np.sum(vap * np.cross(vad, vab, axisa=1, axisb=1), axis=1) / 6.
        vd = np.sum(vap * np.cross(vab, vac, axisa=1, axisb=1), axis=1) / 6.
        v = np.sum(vab * np.cross(vac, vad, axisa=1, axisb=1), axis=1) / 6.
        
        c = np.zeros((4, npts))
        c[0, :] = va / v
        c[1, :] = vb / v
        c[2, :] = vc / v
        c[3, :] = vd / v
        mask = np.zeros(cells.shape).astype(bool)
        mask[cells>0] = np.all(c>0,axis=0)
#         mask= np.all(c>0,axis=0)
#         print(mask[0])

#         print('pi',pos_idx[cells>0][np.all(c>0,axis=0)])
        tetras[np.sum(mask,axis=1).astype(bool)] = cells[mask]
#         bc[np.sum(mask,axis=1).astype(bool),:] = c[:,mask].T
        return tetras#,bc

#         return self.aabb[aabbidx,:]
    def pos_to_aabb_index(self,pos):
        ix = pos[:, 0] - self.origin[None, 0]
        iy = pos[:, 1] - self.origin[None, 1]
        iz = pos[:, 2] - self.origin[None, 2]
        ix = ix // self.step[None, 0]
        iy = iy // self.step[None, 1]
        iz = iz // self.step[None, 2]
        return ix.astype(int)+iy.astype(int)*self.nx+iz.astype(int)*self.nx*self.ny
    
    def global_aabb_index_to_local(self,global_index):
        global_index = np.array(global_index)
        x_index = global_index % self.nx
        y_index = global_index // self.nx % \
                  self.ny
        z_index = global_index // self.nx // \
                  self.ny
        
        return x_index, y_index, z_index
#         corner_pos = self.origin[:,None]+self.step[:,None]*np.vstack([xcorners,ycorners,zcorners])
#         print(corner_pos)

In [154]:
def build(origin,maximum,n_tetra,nx,ny,nz):
    minx = origin[0]
    miny = origin[1]
    minz = origin[2]
    maxx = maximum[0]
    maxy =  maximum[1]
    maxz =  maximum[2]
    points = np.array([
        (minx, miny, minz),
        (maxx, miny, minz),
        (maxx, maxy, minz),
        (minx, maxy, minz),
        (minx, miny, maxz),
        (maxx, miny, maxz),
        (maxx, maxy, maxz),
        (minx, maxy, maxz)
    ])
#         self.surfaces['top'] = (
#             (minx, miny, maxz), (maxx, miny, maxz), (maxx, maxy, maxz),
#             (minx, maxy, maxz))
#         self.surfaces['bottom'] = (
#             (minx, miny, minz), (maxx, miny, minz), (maxx, maxy, minz),
#             (minx, maxy, minz))

#         self.points = points
#         # calculate the 3 principal components to find the local coordinate
#         # system
#         self.pca.fit(points)
#         # project the points into this coordinate system
#         newp = self.pca.transform(points)

    lengthU = maxx - minx
    lengthV = maxy - miny
    lengthW = maxz - minz
    boxVol = lengthU * lengthW * lengthV
    correction_factor = 1.91
    maxvol = correction_factor * boxVol / n_tetra
    facets = [
        [0, 1, 2, 3],
        [4, 5, 6, 7],
        [0, 4, 5, 1],
        [1, 5, 6, 2],
        [2, 6, 7, 3],
        [3, 7, 4, 0]
    ]

    # create the mesh
    info = meshpy.tet.MeshInfo()
    # use the projected points to build the mesh
    info.set_points(points)
    info.set_facets(facets)
    meshpy_mesh = meshpy.tet.build(info, max_volume=maxvol,
                                   options=meshpy.tet.Options('pqn'))
    nodes = np.array(meshpy_mesh.points)
    elements=  np.array(meshpy_mesh.elements, dtype=np.int64)
    neighbours = np.array(meshpy_mesh.neighbors, dtype=np.int64)
    return TetMesh2(origin,maximum,nodes,elements,neighbours,nx,ny,nz)#    def __init__(self,origin,maximum,nodes,tetra,neighbours,nx=10,ny=10,nz=10):


In [155]:
# for i,t in enumerate([100,1000,5000,7000,10000,15000,20000]):#range(1,10):
#     i=i+2
#     print(i*i*i)
x = np.linspace(0.01,.99,20)
y = np.linspace(0.01,.99,20)
z = np.linspace(0.01,.99,20)
xx,yy,zz = np.meshgrid(x,y,z)
points = np.vstack([xx.flatten(),yy.flatten(),zz.flatten()]).T
mesh2 = build([0,0,0],[1,1,1],1000,10,10,10)
#points = np.mean(mesh.nodes[mesh.tetra],axis=1)
#mask = mesh.get_tetra2(points)#np.random.random((100,3)))
# for t in mesh.tetra:
#     points = mesh.nodes[t]
#     try:
#         mesh.get_tetra([np.mean(points,axis=0)])
#     except:
#         print('exception ',i,np.mean(points,axis=0))
#mesh.get_tetra(np.array([[0.69,0.5,.99]]))#np.random.random((100,3)))
# for i in range(100):
#     print(A[i,A[i,:]>0])

[0.1 0.1 0.1]
[[ 0.25 -0.05  0.95]
 [ 0.35 -0.05  0.95]
 [ 0.25  0.05  0.95]
 [ 0.25 -0.05  1.05]
 [ 0.35 -0.05  1.05]
 [ 0.25  0.05  1.05]
 [ 0.35  0.05  0.95]
 [ 0.35  0.05  1.05]]
Couldnt find any tetra
[[ 0.35 -0.05  0.95]
 [ 0.45 -0.05  0.95]
 [ 0.35  0.05  0.95]
 [ 0.35 -0.05  1.05]
 [ 0.45 -0.05  1.05]
 [ 0.35  0.05  1.05]
 [ 0.45  0.05  0.95]
 [ 0.45  0.05  1.05]]
Couldnt find any tetra
[[ 0.45 -0.05  0.95]
 [ 0.55 -0.05  0.95]
 [ 0.45  0.05  0.95]
 [ 0.45 -0.05  1.05]
 [ 0.55 -0.05  1.05]
 [ 0.45  0.05  1.05]
 [ 0.55  0.05  0.95]
 [ 0.55  0.05  1.05]]
Couldnt find any tetra
[[ 0.55 -0.05  0.95]
 [ 0.65 -0.05  0.95]
 [ 0.55  0.05  0.95]
 [ 0.55 -0.05  1.05]
 [ 0.65 -0.05  1.05]
 [ 0.55  0.05  1.05]
 [ 0.65  0.05  0.95]
 [ 0.65  0.05  1.05]]
Couldnt find any tetra
[[ 0.65 -0.05  0.95]
 [ 0.75 -0.05  0.95]
 [ 0.65  0.05  0.95]
 [ 0.65 -0.05  1.05]
 [ 0.75 -0.05  1.05]
 [ 0.65  0.05  1.05]
 [ 0.75  0.05  0.95]
 [ 0.75  0.05  1.05]]
Couldnt find any tetra
[[0.35 0.05 0.95]
 [0.45 0

In [156]:
print(mesh2.aabb[:,0])

[ 17 302 302 ...  79  79  17]


In [157]:
#%%snakeviz
points = np.random.random((10000,3))

In [158]:
aabbidx = mesh2.pos_to_aabb_index(points)
idx = np.arange(0,mesh2.aabb.shape[0])
xi,yi,zi = mesh2.global_aabb_index_to_local(idx[np.all(mesh2.aabb == -1,axis=1)])
# aabbidx[print(aabbidx.shape)]

In [159]:
xi

array([3, 4, 5, 6, 7, 4, 5, 6, 7, 8, 5, 6, 7, 8, 9, 6, 7, 8, 9, 0, 7, 1])

In [160]:
mask2 = mesh2.get_tetrac(points)#np.random.random((100,3)))

101
va < 0
363
vb <0
561
va < 0
589
va < 0
614
va < 0
806
vb <0
-1
12
va < 0
149
vb <0
317
va < 0
351
vb <0
414
va < 0
651
va < 0
800
vb <0
804
vb <0
805
vb <0
851
va < 0
-1
1291
va < 0
-1
18
va < 0
207
vb <0
329
vb <0
726
va < 0
766
va < 0
774
vb <0
-1
40
vc < 0
746
va < 0
854
va < 0
1345
vb <0
-1
126
va < 0
197
vb <0
402
va < 0
405
vc < 0
428
vb <0
440
vb <0
446
va < 0
496
vb <0
507
va < 0
879
vb <0
938
vb <0
978
va < 0
1115
va < 0
1162
va < 0
1238
va < 0
1240
va < 0
1340
va < 0
1349
vb <0
1427
vc < 0
1431
vb <0
1432
vb <0
-1
1285
vb <0
-1
205
vb <0
224
vc < 0
455
va < 0
490
vd < 0
639
vb <0
683
va < 0
934
va < 0
1241
vc < 0
1348
va < 0
-1
1437
-1
182
va < 0
-1
109
va < 0
257
vd < 0
273
va < 0
339
va < 0
504
vb <0
790
vb <0
832
va < 0
835
vb <0
943
va < 0
962
va < 0
966
va < 0
1060
va < 0
1268
va < 0
1275
va < 0
-1
175
vd < 0
984
va < 0
1038
va < 0
1085
va < 0
1186
va < 0
-1
142
va < 0
294
vb <0
1082
vb <0
-1
5
va < 0
59
va < 0
93
va < 0
116
vb <0
785
vb <0
1438
va < 0
1440
va < 0
14

vc < 0
1092
va < 0
1097
va < 0
1099
va < 0
1112
va < 0
1157
vb <0
1220
va < 0
1224
va < 0
1225
vb <0
1227
va < 0
1228
va < 0
-1
15
va < 0
72
vb <0
204
va < 0
245
vb <0
401
va < 0
445
va < 0
714
va < 0
778
va < 0
779
vb <0
839
vb <0
-1
450
va < 0
695
va < 0
1280
vb <0
-1
9
vb <0
188
vb <0
258
vb <0
324
va < 0
344
va < 0
418
vb <0
956
vb <0
1136
vb <0
1139
va < 0
1168
va < 0
1425
vb <0
-1
104
-1
37
vb <0
145
va < 0
286
vb <0
303
va < 0
308
vb <0
353
va < 0
459
va < 0
539
va < 0
743
va < 0
767
va < 0
852
vb <0
1182
va < 0
1184
vb <0
1239
vc < 0
-1
1439
vb <0
-1
1038
va < 0
1119
va < 0
1246
va < 0
-1
1407
vc < 0
-1
648
va < 0
727
va < 0
1036
vc < 0
-1
310
-1
104
vc < 0
-1
111
vb <0
374
va < 0
379
vb <0
686
vb <0
-1
98
va < 0
148
va < 0
172
va < 0
261
va < 0
434
va < 0
479
vb <0
491
vd < 0
549
vb <0
720
va < 0
772
vb <0
814
vc < 0
899
vc < 0
950
va < 0
955
vc < 0
994
vc < 0
1199
vb <0
1261
va < 0
-1
12
va < 0
76
va < 0
207
vb <0
311
vb <0
320
va < 0
329
vb <0
378
va < 0
1015
vb <0
1133
va <

va < 0
433
vb <0
446
va < 0
520
va < 0
536
vc < 0
729
vc < 0
879
vb <0
978
vb <0
989
vc < 0
1037
vc < 0
1039
vd < 0
1160
vc < 0
1162
1314
va < 0
-1
1384
vb <0
-1
21
va < 0
133
va < 0
139
va < 0
142
va < 0
294
va < 0
331
va < 0
375
vb <0
395
vb <0
471
vb <0
549
va < 0
583
vb <0
715
vb <0
903
vb <0
953
va < 0
995
vb <0
1108
va < 0
1206
vb <0
-1
19
va < 0
255
vb <0
281
va < 0
464
va < 0
841
vc < 0
1048
vb <0
1114
vb <0
1163
va < 0
1163
va < 0
1298
vb <0
1302
vb <0
1315
vb <0
1331
va < 0
1333
va < 0
1448
va < 0
-1
85
vb <0
253
va < 0
330
vb <0
369
va < 0
489
va < 0
545
va < 0
730
va < 0
874
vb <0
945
va < 0
963
vb <0
1031
vc < 0
1052
vc < 0
1052
vc < 0
1123
va < 0
1191
va < 0
1309
va < 0
1329
vb <0
1334
va < 0
-1
129
vb <0
721
va < 0
876
va < 0
885
va < 0
968
va < 0
1014
va < 0
1245
vb <0
1247
vb <0
1312
va < 0
-1
62
va < 0
175
vd < 0
1085
va < 0
1245
va < 0
1341
va < 0
1406
vc < 0
-1
16
vb <0
354
va < 0
487
va < 0
516
va < 0
577
va < 0
684
vc < 0
783
va < 0
1064
va < 0
-1
198
va < 0
405
v

va < 0
1107
va < 0
1263
va < 0
1269
va < 0
1272
vb <0
1466
va < 0
1468
va < 0
-1
138
vb <0
160
va < 0
211
vb <0
254
va < 0
280
va < 0
282
va < 0
300
vc < 0
309
va < 0
357
va < 0
357
va < 0
367
vb <0
373
va < 0
389
vd < 0
390
vb <0
407
vb <0
457
vb <0
622
va < 0
674
vb <0
698
va < 0
717
va < 0
723
va < 0
723
va < 0
736
vc < 0
784
va < 0
841
vb <0
844
va < 0
945
va < 0
977
va < 0
985
va < 0
1005
va < 0
1013
va < 0
1053
va < 0
1113
vc < 0
1120
vb <0
1181
va < 0
1183
va < 0
1235
vc < 0
1322
vc < 0
1322
vc < 0
1388
vc < 0
1436
va < 0
1440
va < 0
1441
vb <0
1454
vb <0
-1
516
va < 0
638
vb <0
651
va < 0
652
vb <0
799
vb <0
800
vb <0
-1
330
vb <0
854
va < 0
1119
vb <0
-1
171
va < 0
284
vb <0
288
va < 0
307
va < 0
399
va < 0
519
va < 0
562
va < 0
807
vb <0
810
vb <0
965
va < 0
1165
va < 0
1255
vb <0
1413
va < 0
1414
vb <0
1415
va < 0
-1
113
vb <0
532
vd < 0
629
va < 0
781
vb <0
1031
vc < 0
1231
vb <0
1262
va < 0
1313
va < 0
1362
vc < 0
1363
vb <0
1369
va < 0
-1
9
vb <0
272
vb <0
956
vb <0
1136


292
vb <0
-1
111
vb <0
374
va < 0
685
va < 0
1150
va < 0
1482
va < 0
-1
99
va < 0
123
vb <0
758
vb <0
1077
va < 0
1464
va < 0
-1
1108
vd < 0
-1
61
va < 0
86
va < 0
90
vc < 0
238
va < 0
472
va < 0
604
va < 0
997
va < 0
1105
va < 0
1261
vd < 0
1270
va < 0
1271
vb <0
1344
vb <0
1347
va < 0
-1
44
vd < 0
290
vc < 0
332
vb <0
416
va < 0
552
vb <0
565
va < 0
566
vc < 0
745
vd < 0
932
vb <0
969
vb <0
970
vd < 0
1032
va < 0
1084
vb <0
1170
vc < 0
1203
vc < 0
1216
vb <0
1296
vd < 0
1301
vd < 0
1303
va < 0
1316
va < 0
1439
vc < 0
-1
320
va < 0
378
va < 0
801
va < 0
-1
172
va < 0
471
vb <0
476
vd < 0
484
va < 0
491
vd < 0
522
vb <0
670
vb <0
772
vb <0
802
vb <0
814
vd < 0
897
va < 0
903
vb <0
949
vd < 0
994
vc < 0
1046
vc < 0
1202
vd < 0
1320
vb <0
1321
vb <0
1337
vc < 0
-1
58
va < 0
415
va < 0
447
va < 0
629
va < 0
771
vc < 0
781
va < 0
913
va < 0
922
va < 0
936
va < 0
1158
va < 0
1351
va < 0
1359
vb <0
1366
vc < 0
1370
va < 0
-1
607
va < 0
899
vc < 0
1324
va < 0
1409
va < 0
-1
175
vb <0
477
vb <

1398
va < 0
-1
46
va < 0
290
vc < 0
307
va < 0
371
va < 0
456
vc < 0
473
va < 0
552
vb <0
842
va < 0
932
vd < 0
969
vb <0
970
va < 0
998
va < 0
1032
va < 0
1216
vb <0
1251
vb <0
1254
va < 0
1256
va < 0
1258
vb <0
1260
va < 0
1278
vb <0
1281
va < 0
1295
vb <0
1296
vd < 0
1316
va < 0
1398
va < 0
1399
vb <0
1407
vb <0
-1
39
vc < 0
44
vb <0
352
va < 0
567
va < 0
710
va < 0
724
va < 0
794
vb <0
996
vb <0
1050
va < 0
-1
202
va < 0
336
va < 0
355
vc < 0
509
va < 0
1325
va < 0
-1
513
-1
220
va < 0
646
vb <0
647
vb <0
-1
43
va < 0
55
vb <0
184
vb <0
289
va < 0
438
va < 0
439
vb <0
513
vc < 0
611
vb <0
689
va < 0
738
vb <0
795
vb <0
864
vb <0
896
vb <0
1079
va < 0
1098
va < 0
1099
va < 0
1171
va < 0
1220
vb <0
1221
va < 0
1222
vc < 0
1224
va < 0
1225
vb <0
1227
va < 0
1228
va < 0
1393
va < 0
1462
va < 0
-1
1075
vb <0
-1
15
va < 0
245
vb <0
322
vb <0
445
va < 0
1490
va < 0
1493
vc < 0
-1
417
va < 0
-1
32
va < 0
371
va < 0
388
vb <0
453
va < 0
749
va < 0
923
vc < 0
928
vc < 0
1051
vb <0
1056
va < 

va < 0
-1
143
va < 0
158
va < 0
254
va < 0
300
va < 0
327
va < 0
373
va < 0
384
va < 0
468
vb <0
484
vc < 0
670
vb <0
784
va < 0
854
va < 0
925
va < 0
929
vc < 0
952
va < 0
961
vb <0
1046
vd < 0
1202
vb <0
1246
va < 0
1328
va < 0
1401
va < 0
1474
va < 0
1475
va < 0
1476
va < 0
1479
vb <0
-1
1440
vb <0
-1
31
vc < 0
71
va < 0
757
va < 0
1464
vb <0
1469
vb <0
-1
244
vb <0
742
va < 0
919
vb <0
1044
va < 0
-1
592
vb <0
1471
va < 0
-1
379
vb <0
398
va < 0
-1
93
va < 0
219
va < 0
785
vb <0
1438
va < 0
1448
va < 0
-1
342
vb <0
355
vc < 0
371
vb <0
388
vb <0
509
va < 0
1056
vc < 0
1299
va < 0
1408
vc < 0
1415
va < 0
1489
vb <0
-1
29
vc < 0
43
va < 0
168
va < 0
184
vb <0
381
vb <0
419
va < 0
421
va < 0
506
vb <0
594
va < 0
675
va < 0
995
vb <0
1094
vb <0
1171
va < 0
1380
vc < 0
1380
vc < 0
1393
va < 0
1455
va < 0
1459
va < 0
1462
va < 0
-1
196
va < 0
286
vb <0
426
vb <0
539
va < 0
588
vd < 0
658
vc < 0
1287
va < 0
-1
121
vb <0
435
va < 0
444
vb <0
538
vb <0
556
vc < 0
668
va < 0
729
va < 0
836
v

va < 0
1415
va < 0
-1
80
va < 0
130
va < 0
392
vc < 0
483
va < 0
584
vb <0
640
vb <0
740
va < 0
846
va < 0
863
vc < 0
1002
va < 0
1004
vb <0
1377
vc < 0
1378
vb <0
1470
vc < 0
-1
71
va < 0
78
va < 0
442
va < 0
493
vb <0
563
va < 0
618
va < 0
761
vc < 0
765
vb <0
816
vb <0
822
vb <0
867
vb <0
882
vc < 0
891
vb <0
1095
va < 0
1376
vc < 0
1378
vb <0
-1
902
va < 0
-1
1150
va < 0
1482
va < 0
-1
102
vb <0
212
vb <0
340
vd < 0
387
vc < 0
523
vd < 0
660
va < 0
788
va < 0
796
vd < 0
924
va < 0
1043
va < 0
1072
vc < 0
1141
va < 0
1141
va < 0
1143
vc < 0
1161
vb <0
1177
va < 0
1185
vc < 0
1192
va < 0
1232
vd < 0
1248
vd < 0
1297
va < 0
1360
vc < 0
1396
vb <0
1402
vb <0
-1
40
vb <0
123
vb <0
572
va < 0
629
va < 0
791
va < 0
1031
vc < 0
1154
va < 0
1231
vb <0
1362
vc < 0
-1
135
va < 0
171
va < 0
187
va < 0
250
va < 0
499
va < 0
576
vb <0
692
vb <0
807
vb <0
810
va < 0
1413
va < 0
1414
vb <0
-1
19
va < 0
255
vb <0
281
va < 0
464
va < 0
841
vc < 0
1048
vb <0
1114
vb <0
1163
va < 0
1163
va < 0
1298
vb

500
va < 0
1273
vb <0
-1
649
vb <0
898
vb <0
1183
va < 0
1403
va < 0
1440
va < 0
1441
vb <0
-1
398
va < 0
-1
218
vc < 0
232
vb <0
263
va < 0
318
vb <0
423
vc < 0
558
va < 0
559
va < 0
587
vb <0
883
vb <0
951
vb <0
1223
vc < 0
1466
va < 0
1470
vb <0
-1
207
vb <0
320
va < 0
329
vb <0
378
va < 0
-1
62
vc < 0
626
va < 0
1066
va < 0
1085
vc < 0
1465
va < 0
1467
vb <0
-1
25
vb <0
69
vb <0
121
vb <0
190
va < 0
234
vc < 0
435
va < 0
537
vb <0
556
vc < 0
634
vb <0
777
vd < 0
819
vc < 0
932
vc < 0
1089
va < 0
1102
vb <0
1255
va < 0
1264
vd < 0
1281
va < 0
-1
44
vd < 0
68
va < 0
114
va < 0
205
vb <0
290
vc < 0
332
vb <0
416
va < 0
490
vd < 0
552
vb <0
683
va < 0
923
vc < 0
954
vc < 0
986
va < 0
986
va < 0
1032
va < 0
1051
vb <0
1057
va < 0
1168
vb <0
1170
vd < 0
1216
vb <0
1296
vd < 0
-1
131
va < 0
170
va < 0
170
va < 0
207
vb <0
320
va < 0
329
vb <0
378
vb <0
577
va < 0
679
va < 0
709
vb <0
732
va < 0
769
vb <0
931
vb <0
1137
va < 0
1140
va < 0
-1
91
vb <0
173
va < 0
768
vb <0
988
va < 0
1001
vb

va < 0
754
va < 0
792
va < 0
850
va < 0
890
vc < 0
1079
vb <0
1088
va < 0
1472
va < 0
-1
503
-1
44
vb <0
290
vc < 0
332
vb <0
416
vd < 0
552
vb <0
565
va < 0
566
vc < 0
745
vd < 0
932
vd < 0
969
vb <0
970
va < 0
1032
va < 0
1084
vb <0
1170
vd < 0
1203
vc < 0
1216
vb <0
1296
vd < 0
1301
va < 0
1303
va < 0
1316
va < 0
1439
vc < 0
-1
111
vb <0
374
va < 0
685
va < 0
-1
192
vb <0
247
vc < 0
358
va < 0
436
va < 0
456
vc < 0
514
va < 0
551
vc < 0
616
va < 0
616
va < 0
769
vb <0
794
vb <0
808
vb <0
843
vc < 0
989
vc < 0
1028
vb <0
1057
va < 0
1160
vc < 0
1252
va < 0
1254
va < 0
1295
vb <0
-1
3
vb <0
143
vc < 0
158
va < 0
432
vc < 0
506
va < 0
1323
va < 0
1327
vb <0
1404
vb <0
1481
vc < 0
1485
va < 0
-1
118
va < 0
188
vb <0
793
va < 0
845
va < 0
1101
vb <0
1339
va < 0
1428
va < 0
1429
va < 0
-1
375
vc < 0
394
vd < 0
603
va < 0
929
va < 0
949
vc < 0
1168
vc < 0
1314
va < 0
-1
415
va < 0
613
vb <0
1350
va < 0
-1
277
va < 0
319
va < 0
342
vb <0
512
va < 0
688
vc < 0
1300
vb <0
-1
30
vc < 0
33
va <

496
vc < 0
552
vb <0
668
va < 0
684
va < 0
716
vb <0
716
vb <0
732
va < 0
783
vb <0
842
va < 0
843
vc < 0
879
vb <0
923
vc < 0
933
va < 0
986
vb <0
986
vb <0
998
va < 0
1032
va < 0
1051
vb <0
1115
vd < 0
1142
vb <0
1216
vb <0
1251
vb <0
1254
va < 0
1258
vb <0
1260
va < 0
1278
vb <0
1281
va < 0
1295
vc < 0
1296
vc < 0
1399
vb <0
-1
345
vd < 0
444
va < 0
537
vb <0
668
vc < 0
836
vb <0
1081
vb <0
1089
va < 0
1292
vb <0
-1
76
va < 0
-1
948
vb <0
973
vb <0
994
vb <0
1082
vb <0
-1
517
va < 0
-1
541
va < 0
624
vb <0
731
va < 0
864
vb <0
893
vb <0
981
vd < 0
1008
va < 0
1098
va < 0
1222
va < 0
-1
189
va < 0
236
vb <0
542
vb <0
557
va < 0
691
vb <0
694
va < 0
840
va < 0
1305
va < 0
-1
132
va < 0
271
vb <0
-1
26
va < 0
49
vb <0
175
vb <0
241
vc < 0
339
va < 0
408
va < 0
540
va < 0
573
va < 0
744
va < 0
763
va < 0
899
vc < 0
943
vb <0
962
vb <0
968
vb <0
1061
va < 0
1174
va < 0
1276
va < 0
1279
va < 0
1412
va < 0
1419
va < 0
1437
vb <0
-1
352
vd < 0
-1
649
vb <0
898
vb <0
1183
va < 0
1403
va < 0


vb <0
649
va < 0
811
vb <0
898
va < 0
1454
vb <0
-1
131
va < 0
527
va < 0
-1
180
va < 0
262
va < 0
725
vc < 0
735
vb <0
1071
va < 0
-1
28
vd < 0
47
vb <0
50
vb <0
134
vb <0
197
vb <0
330
vc < 0
440
va < 0
448
vb <0
554
va < 0
664
va < 0
666
vd < 0
941
vc < 0
983
vc < 0
1037
va < 0
1039
vb <0
1074
vc < 0
1237
vd < 0
1330
vc < 0
1476
vb <0
1484
vb <0
1486
va < 0
-1
212
vb <0
235
va < 0
387
vc < 0
523
va < 0
565
va < 0
566
vc < 0
660
va < 0
745
vd < 0
749
va < 0
796
va < 0
924
va < 0
932
vb <0
969
vb <0
970
vd < 0
1043
va < 0
1072
vb <0
1161
vb <0
1177
va < 0
1185
vc < 0
1192
va < 0
1203
vc < 0
1232
vd < 0
1297
va < 0
1303
vd < 0
1360
vb <0
1368
va < 0
1372
vc < 0
1394
vc < 0
1396
vb <0
1402
va < 0
-1
2
va < 0
157
vb <0
214
va < 0
265
vb <0
475
va < 0
492
va < 0
502
vb <0
546
vb <0
546
vb <0
648
vb <0
727
vd < 0
782
vb <0
-1
370
vb <0
649
va < 0
811
vb <0
898
va < 0
1454
vb <0
-1
238
vc < 0
255
vb <0
366
va < 0
1069
va < 0
1180
vb <0
-1
80
vb <0
155
vc < 0
177
vb <0
304
vb <0
472
va < 0
5

-1
202
va < 0
336
va < 0
355
va < 0
359
vb <0
509
vb <0
571
va < 0
928
va < 0
1057
va < 0
1179
vc < 0
1299
va < 0
1418
vc < 0
1421
va < 0
-1
1305
va < 0
-1
96
vc < 0
197
vc < 0
665
va < 0
942
vb <0
987
va < 0
1045
va < 0
1238
vb <0
1426
vb <0
1457
vc < 0
1461
vb <0
-1
1081
va < 0
-1
42
vb <0
634
vb <0
1009
vd < 0
1021
vb <0
1193
vd < 0
1255
va < 0
-1
1291
-1
278
va < 0
384
va < 0
579
vc < 0
649
vb <0
733
vb <0
1054
vb <0
1328
va < 0
1401
va < 0
1404
va < 0
1474
va < 0
1475
va < 0
1480
va < 0
-1
35
va < 0
53
va < 0
209
vb <0
242
vb <0
257
va < 0
339
va < 0
462
va < 0
687
vb <0
818
va < 0
823
vb <0
880
va < 0
962
va < 0
1070
vd < 0
1116
vd < 0
1118
va < 0
1127
va < 0
1138
va < 0
-1
4
vb <0
362
vb <0
432
vc < 0
624
vb <0
705
va < 0
706
va < 0
751
vb <0
751
vb <0
754
va < 0
-1
238
vc < 0
255
vb <0
366
va < 0
1069
va < 0
1180
vb <0
-1
102
vb <0
212
vb <0
340
vd < 0
387
vc < 0
523
vd < 0
660
va < 0
788
va < 0
796
va < 0
924
va < 0
1043
va < 0
1072
vc < 0
1141
va < 0
1141
va < 0
1143
vc < 0
1

-1
28
va < 0
50
va < 0
554
vb <0
983
vc < 0
1187
va < 0
1318
va < 0
1331
va < 0
1334
va < 0
1475
va < 0
-1
154
vb <0
208
va < 0
447
vb <0
601
va < 0
855
vb <0
869
va < 0
1158
vb <0
1351
vc < 0
1358
vb <0
1359
va < 0
-1
121
vb <0
190
va < 0
234
vb <0
274
vd < 0
435
va < 0
556
vc < 0
565
va < 0
566
vc < 0
603
va < 0
819
va < 0
932
vd < 0
955
va < 0
1084
vb <0
1102
va < 0
1453
va < 0
-1
18
va < 0
131
va < 0
207
vb <0
329
vb <0
527
va < 0
726
va < 0
766
va < 0
774
vb <0
1132
vb <0
1140
va < 0
-1
455
vb <0
1196
vc < 0
1241
vb <0
1342
vb <0
1430
vb <0
1431
va < 0
-1
48
vb <0
570
vc < 0
709
vb <0
799
va < 0
-1
585
va < 0
650
va < 0
650
va < 0
712
va < 0
1211
vb <0
-1
885
vd < 0
-1
64
vb <0
299
vd < 0
916
vb <0
1022
vb <0
1052
vc < 0
1052
vc < 0
1074
vb <0
1088
va < 0
1156
vc < 0
1237
va < 0
1238
vd < 0
1332
va < 0
1336
va < 0
1340
va < 0
1349
vb <0
1471
vb <0
1472
vb <0
1473
vd < 0
-1
835
-1
66
vb <0
145
vb <0
230
va < 0
286
vb <0
296
vc < 0
331
va < 0
426
vb <0
521
va < 0
539
va < 0
633
va <

vd < 0
446
va < 0
666
vc < 0
862
vb <0
978
vb <0
1037
vc < 0
1039
va < 0
-1
113
vb <0
532
vc < 0
629
va < 0
781
vb <0
1031
vc < 0
1231
vb <0
1262
va < 0
1313
va < 0
1362
vc < 0
1363
vb <0
1369
va < 0
-1
122
va < 0
244
vb <0
313
vb <0
574
vb <0
662
vb <0
687
va < 0
718
va < 0
823
va < 0
919
vb <0
990
va < 0
999
vb <0
1109
va < 0
1126
va < 0
1138
va < 0
-1
104
va < 0
117
va < 0
148
va < 0
595
va < 0
865
vc < 0
990
vb <0
1078
vb <0
1210
va < 0
-1
237
vb <0
1488
vb <0
-1
278
va < 0
898
va < 0
-1
42
vb <0
119
va < 0
192
vb <0
241
va < 0
359
vb <0
430
va < 0
458
va < 0
710
vb <0
777
vc < 0
1009
vb <0
1021
vb <0
1160
vc < 0
1193
va < 0
1264
vd < 0
1450
va < 0
-1
119
vb <0
180
vb <0
192
vb <0
333
va < 0
433
vb <0
931
vb <0
989
va < 0
1057
va < 0
1160
vc < 0
-1
185
va < 0
227
va < 0
380
va < 0
418
va < 0
470
vb <0
712
va < 0
1101
vb <0
-1
35
va < 0
53
va < 0
209
vb <0
242
vb <0
257
va < 0
339
va < 0
462
va < 0
687
vb <0
818
vb <0
823
vb <0
880
va < 0
962
va < 0
1070
vd < 0
1116
vd < 0
1118
va <

vb <0
1400
va < 0
1403
va < 0
-1
1029
vc < 0
-1
278
va < 0
898
va < 0
-1
236
vb <0
239
va < 0
391
va < 0
396
va < 0
452
va < 0
-1
233
va < 0
609
vb <0
700
va < 0
702
vc < 0
-1
510
va < 0
646
vb <0
975
vb <0
1125
va < 0
-1
166
va < 0
232
vb <0
360
va < 0
400
va < 0
527
va < 0
544
vb <0
656
va < 0
667
va < 0
679
va < 0
781
vb <0
786
va < 0
791
va < 0
797
va < 0
959
va < 0
1010
va < 0
1016
va < 0
1137
va < 0
1358
va < 0
1366
va < 0
-1
363
va < 0
497
vb <0
522
va < 0
614
va < 0
715
vb <0
806
vb <0
1201
va < 0
-1
89
119
va < 0
192
vc < 0
241
va < 0
359
vb <0
393
vd < 0
395
vc < 0
430
va < 0
565
va < 0
590
vd < 0
710
va < 0
1084
vb <0
1160
vc < 0
1450
va < 0
-1
369
va < 0
489
va < 0
545
va < 0
730
va < 0
963
vb <0
1309
va < 0
1329
vb <0
1334
va < 0
-1
118
va < 0
555
va < 0
773
vd < 0
-1
260
va < 0
338
vc < 0
406
va < 0
595
va < 0
687
va < 0
888
va < 0
950
vb <0
1078
vb <0
1104
vb <0
1116
va < 0
1117
va < 0
1118
vb <0
1125
va < 0
1127
vc < 0
-1
19
vc < 0
534
vc < 0
632
vc < 0
1347
vb <0
-1
11

vb <0
314
va < 0
394
va < 0
583
va < 0
637
va < 0
825
va < 0
1024
va < 0
1091
vc < 0
1110
va < 0
-1
212
vb <0
235
vd < 0
387
vc < 0
523
va < 0
565
va < 0
566
vc < 0
660
va < 0
745
vb <0
749
vd < 0
796
va < 0
924
va < 0
932
vb <0
969
vb <0
970
vb <0
1043
va < 0
1072
vc < 0
1161
vb <0
1177
va < 0
1185
vc < 0
1192
va < 0
1203
vc < 0
1232
vd < 0
1297
va < 0
1303
vd < 0
1360
vc < 0
1368
va < 0
1372
va < 0
1394
va < 0
1396
vb <0
1402
va < 0
-1
246
va < 0
467
va < 0
605
va < 0
867
va < 0
1267
va < 0
1282
va < 0
1494
va < 0
-1
145
vb <0
264
va < 0
286
vb <0
296
vc < 0
353
va < 0
426
vb <0
539
va < 0
892
va < 0
1128
vb <0
1184
vb <0
-1
145
vb <0
296
vb <0
588
vd < 0
992
vb <0
1128
vb <0
1184
vb <0
1287
vc < 0
1288
va < 0
-1
1024
va < 0
-1
277
va < 0
319
va < 0
342
vb <0
512
va < 0
688
vc < 0
1300
vb <0
-1
145
vb <0
296
vb <0
588
vd < 0
992
vb <0
1128
vb <0
1184
vb <0
1287
vc < 0
1288
va < 0
-1
131
va < 0
1134
vc < 0
-1
92
vb <0
933
va < 0
-1
97
va < 0
220
va < 0
268
vc < 0
647
vb <0
704
vb <0
8

va < 0
905
vc < 0
926
vb <0
927
va < 0
948
vb <0
973
vb <0
994
va < 0
1035
va < 0
1124
vc < 0
1129
vb <0
1208
va < 0
1284
vb <0
1285
vc < 0
1286
va < 0
1289
va < 0
1290
vb <0
-1
1122
vb <0
1239
vc < 0
-1
196
va < 0
331
va < 0
521
vc < 0
526
vb <0
549
vd < 0
590
va < 0
607
vb <0
633
vb <0
658
va < 0
953
vc < 0
1288
vb <0
-1
17
va < 0
391
vb <0
396
vb <0
602
va < 0
1025
va < 0
1371
va < 0
-1
21
vb <0
133
va < 0
139
va < 0
142
va < 0
294
va < 0
331
va < 0
375
va < 0
395
vb <0
471
vb <0
549
vb <0
583
va < 0
715
vb <0
903
vb <0
953
va < 0
995
vb <0
1108
va < 0
1206
vb <0
-1
48
va < 0
112
va < 0
174
vb <0
455
va < 0
632
va < 0
677
vb <0
-1
143
vb <0
158
va < 0
168
va < 0
314
va < 0
594
va < 0
637
vc < 0
670
vb <0
961
va < 0
1024
va < 0
1108
va < 0
1110
vc < 0
1206
vd < 0
1323
va < 0
1326
va < 0
1404
vb <0
1479
vd < 0
1480
vb <0
-1
363
va < 0
434
va < 0
491
vd < 0
515
va < 0
515
va < 0
522
va < 0
711
vc < 0
720
va < 0
789
vd < 0
865
va < 0
875
vb <0
905
va < 0
927
vc < 0
948
vc < 0
973
vc < 0

vb <0
1453
va < 0
-1
487
va < 0
516
va < 0
577
va < 0
651
va < 0
732
vb <0
769
vb <0
800
vb <0
804
vb <0
805
vb <0
-1
89
vd < 0
164
vc < 0
356
va < 0
411
va < 0
520
vd < 0
536
va < 0
666
va < 0
862
vb <0
929
vc < 0
949
vb <0
1162
vb <0
1327
vb <0
1389
va < 0
1462
va < 0
-1
1049
vb <0
-1
573
vb <0
-1
124
vc < 0
182
va < 0
437
va < 0
518
va < 0
737
va < 0
924
vb <0
1034
va < 0
1161
vb <0
1185
va < 0
1232
vb <0
1269
va < 0
1270
va < 0
1283
va < 0
1297
va < 0
1360
vb <0
1368
vc < 0
1372
vc < 0
1396
va < 0
1411
va < 0
1422
va < 0
1422
va < 0
-1
122
va < 0
169
va < 0
313
vb <0
574
vb <0
662
vb <0
742
va < 0
823
va < 0
1044
va < 0
-1
67
vc < 0
82
va < 0
160
va < 0
176
vb <0
211
va < 0
254
va < 0
280
va < 0
300
vc < 0
321
va < 0
327
va < 0
373
va < 0
407
vb <0
468
va < 0
579
vb <0
704
vb <0
733
vb <0
736
va < 0
784
va < 0
830
vc < 0
854
va < 0
925
va < 0
946
vb <0
952
vc < 0
985
va < 0
1013
va < 0
1020
va < 0
1054
vb <0
1113
vc < 0
1246
va < 0
1320
va < 0
-1
320
va < 0
378
va < 0
801
va < 0
-1

vb <0
1101
va < 0
1133
va < 0
1135
va < 0
1242
va < 0
1244
va < 0
-1
414
vc < 0
-1
126
va < 0
197
vb <0
402
va < 0
405
vc < 0
428
vb <0
440
vb <0
446
va < 0
496
vb <0
507
va < 0
879
vb <0
938
vb <0
978
va < 0
1115
va < 0
1162
va < 0
1238
va < 0
1240
va < 0
1340
va < 0
1349
vb <0
1427
vc < 0
1431
vb <0
1432
vb <0
-1
230
va < 0
866
va < 0
897
va < 0
961
va < 0
1091
vc < 0
1201
va < 0
1204
va < 0
1205
va < 0
1209
va < 0
1291
vc < 0
-1
98
va < 0
508
va < 0
660
va < 0
930
va < 0
992
va < 0
1012
va < 0
1143
vb <0
1325
va < 0
-1
73
vb <0
74
va < 0
108
va < 0
505
va < 0
801
va < 0
803
vc < 0
-1
95
va < 0
203
va < 0
219
vb <0
310
va < 0
315
vb <0
569
va < 0
655
vb <0
661
vb <0
701
vb <0
703
vb <0
1435
va < 0
1443
va < 0
1444
va < 0
1448
vb <0
1449
va < 0
-1
201
vb <0
-1
25
va < 0
69
vc < 0
94
vb <0
229
vb <0
267
va < 0
325
va < 0
325
va < 0
364
vb <0
458
vb <0
481
va < 0
537
vb <0
634
va < 0
747
vb <0
894
va < 0
1009
vb <0
1014
va < 0
1063
va < 0
1075
va < 0
1089
va < 0
1256
va < 0
1258
va < 0


734
vc < 0
770
vb <0
829
vb <0
916
vb <0
1027
vb <0
1048
vd < 0
1049
va < 0
1151
va < 0
1329
vb <0
1330
va < 0
1331
va < 0
1332
va < 0
1333
vb <0
-1
219
va < 0
384
va < 0
579
vc < 0
1054
vb <0
1183
va < 0
1404
va < 0
1452
vb <0
1481
va < 0
1485
va < 0
-1
10
vc < 0
376
vb <0
775
vb <0
778
va < 0
779
vb <0
853
vb <0
860
vb <0
914
va < 0
914
va < 0
915
vb <0
1282
va < 0
1410
va < 0
1420
va < 0
-1
189
va < 0
236
vb <0
542
vb <0
557
va < 0
691
vb <0
694
vb <0
840
va < 0
1305
va < 0
-1
27
-1
12
va < 0
311
vb <0
1015
vb <0
1133
va < 0
1159
vb <0
-1
30
vc < 0
33
va < 0
328
va < 0
829
va < 0
1067
vb <0
1151
va < 0
1444
va < 0
-1
175
vb <0
477
vb <0
1119
va < 0
-1
38
va < 0
272
vb <0
580
va < 0
593
va < 0
596
va < 0
734
vc < 0
753
va < 0
792
va < 0
956
va < 0
1026
va < 0
1330
vb <0
1338
vb <0
-1
154
va < 0
222
va < 0
400
vb <0
725
vc < 0
774
vb <0
869
va < 0
870
va < 0
1352
va < 0
-1
209
va < 0
510
va < 0
880
vb <0
975
va < 0
1117
va < 0
1125
va < 0
-1
31
va < 0
109
va < 0
259
vc < 0
273
va < 0


va < 0
-1
68
vb <0
560
vc < 0
954
vc < 0
964
va < 0
986
va < 0
986
va < 0
1168
vb <0
1196
va < 0
1343
vb <0
1348
va < 0
-1
1384
vb <0
-1
366
vb <0
417
va < 0
453
va < 0
1453
vb <0
-1
32
vc < 0
114
va < 0
451
va < 0
453
va < 0
668
va < 0
928
vc < 0
934
va < 0
1056
vc < 0
1256
vb <0
1300
vb <0
1317
va < 0
1398
va < 0
-1
42
va < 0
212
vb <0
215
vb <0
251
vb <0
336
va < 0
355
va < 0
387
vc < 0
430
va < 0
509
vb <0
1006
vb <0
1021
va < 0
1023
va < 0
1040
va < 0
1176
va < 0
1179
vc < 0
1185
vc < 0
1192
va < 0
1193
va < 0
1253
va < 0
1273
vc < 0
1297
va < 0
1396
vb <0
1416
vb <0
1418
vc < 0
1421
va < 0
1492
va < 0
-1
126
va < 0
197
va < 0
402
va < 0
405
vc < 0
428
vb <0
440
vb <0
446
va < 0
496
vb <0
507
va < 0
879
vb <0
938
vb <0
978
va < 0
1115
va < 0
1162
va < 0
1238
va < 0
1240
va < 0
1340
va < 0
1349
vb <0
1427
vc < 0
1431
vb <0
1432
vb <0
-1
1384
vb <0
-1
5
vb <0
134
vb <0
377
va < 0
592
vb <0
1484
vb <0
1486
va < 0
-1
16
vb <0
354
va < 0
487
va < 0
516
va < 0
577
va < 0
684
vc < 0
783


218
vc < 0
871
vc < 0
984
vb <0
1085
va < 0
1308
vb <0
-1
987
vc < 0
1238
vd < 0
-1
260
va < 0
338
vc < 0
406
va < 0
595
va < 0
687
va < 0
888
va < 0
950
vb <0
1078
vb <0
1104
vb <0
1116
va < 0
1117
va < 0
1118
vb <0
1125
va < 0
1127
vc < 0
-1
1218
vd < 0
-1
233
va < 0
609
vb <0
700
va < 0
702
vc < 0
-1
11
vb <0
37
vb <0
66
vb <0
145
vb <0
223
va < 0
286
vb <0
303
va < 0
308
vb <0
334
va < 0
521
va < 0
539
va < 0
630
vb <0
633
va < 0
743
va < 0
767
va < 0
768
vb <0
852
vb <0
920
va < 0
988
va < 0
1076
vd < 0
1182
va < 0
1184
vb <0
1395
vb <0
-1
120
vb <0
335
vc < 0
598
vb <0
653
vc < 0
752
va < 0
825
va < 0
1086
vb <0
1146
vc < 0
1423
vb <0
-1
202
va < 0
251
vb <0
479
vd < 0
763
vb <0
776
vb <0
1174
vc < 0
1185
va < 0
1257
vb <0
1273
va < 0
1279
vb <0
1297
va < 0
1325
va < 0
1396
va < 0
1411
va < 0
1437
vc < 0
1492
va < 0
-1
38
va < 0
269
va < 0
328
va < 0
511
va < 0
593
va < 0
829
va < 0
1047
va < 0
1121
va < 0
1151
va < 0
1152
va < 0
1446
vb <0
1472
vb <0
1483
va < 0
-1
278
va < 0
67

1335
va < 0
-1
259
va < 0
543
vc < 0
572
va < 0
1077
vc < 0
1131
vb <0
1154
va < 0
1247
vc < 0
1379
vb <0
1469
vb <0
-1
1311
-1
1353
va < 0
1371
va < 0
-1
95
va < 0
233
va < 0
315
vb <0
498
vb <0
569
va < 0
609
vb <0
612
va < 0
700
va < 0
702
vb <0
1443
va < 0
1449
va < 0
-1
193
vb <0
281
va < 0
400
vb <0
469
vc < 0
620
vb <0
780
va < 0
1155
vb <0
1242
va < 0
1294
va < 0
-1
1032
vc < 0
-1
118
va < 0
144
vb <0
276
va < 0
369
va < 0
489
va < 0
545
va < 0
555
va < 0
627
vb <0
1026
va < 0
1329
vb <0
1338
va < 0
1339
va < 0
1340
va < 0
1349
va < 0
-1
201
-1
136
vb <0
248
vb <0
626
vb <0
748
vb <0
817
va < 0
1066
va < 0
-1
417
va < 0
-1
237
va < 0
-1
12
va < 0
311
vb <0
1015
vb <0
1133
va < 0
1159
vb <0
-1
363
va < 0
434
va < 0
720
va < 0
789
vd < 0
865
vc < 0
875
vb <0
905
vb <0
927
vc < 0
1199
vb <0
1200
vb <0
1208
va < 0
1290
va < 0
-1
232
va < 0
415
va < 0
587
vc < 0
613
vb <0
771
va < 0
781
vb <0
791
vc < 0
1010
va < 0
1358
vb <0
1366
vb <0
-1
411
va < 0
422
vb <0
427
vb <0
521
va < 0
9

va < 0
1244
va < 0
-1
2
va < 0
157
vb <0
214
va < 0
475
va < 0
492
va < 0
502
va < 0
600
va < 0
782
vb <0
-1
438
va < 0
439
vb <0
848
va < 0
907
va < 0
1092
va < 0
1226
va < 0
1460
va < 0
1463
va < 0
-1
134
vb <0
1330
vb <0
1484
vb <0
1486
va < 0
-1
772
vb <0
-1
252
va < 0
359
vb <0
463
vb <0
536
vb <0
1084
vb <0
-1
353
va < 0
459
va < 0
-1
212
vb <0
235
va < 0
387
vc < 0
523
va < 0
565
va < 0
566
vc < 0
660
va < 0
745
vd < 0
749
va < 0
796
vb <0
924
va < 0
932
va < 0
969
vb <0
970
va < 0
1043
va < 0
1072
vc < 0
1161
vb <0
1177
va < 0
1185
vc < 0
1192
va < 0
1203
vc < 0
1232
vd < 0
1297
va < 0
1303
vb <0
1360
vb <0
1368
va < 0
1372
vc < 0
1394
va < 0
1396
vb <0
1402
va < 0
-1
4
vb <0
5
vb <0
93
va < 0
377
va < 0
379
vb <0
398
va < 0
592
vb <0
671
va < 0
785
va < 0
850
va < 0
-1
39
vd < 0
-1
140
va < 0
195
va < 0
251
vb <0
288
va < 0
307
va < 0
372
vb <0
388
vb <0
500
vb <0
749
va < 0
750
va < 0
796
va < 0
809
va < 0
932
vb <0
969
vb <0
970
vd < 0
1023
va < 0
1040
va < 0
1090
va < 0
116

va < 0
1459
va < 0
1473
va < 0
1478
va < 0
-1
316
vb <0
1033
va < 0
-1
205
vb <0
224
vc < 0
455
va < 0
490
vd < 0
639
vb <0
683
va < 0
934
va < 0
1241
vc < 0
1348
va < 0
-1
47
vb <0
64
va < 0
110
vc < 0
269
va < 0
330
vb <0
862
vc < 0
916
vb <0
1052
vb <0
1052
vb <0
1187
va < 0
1330
vc < 0
1331
vb <0
1332
vb <0
1334
vc < 0
1446
vb <0
1471
vb <0
1472
vc < 0
1473
vb <0
1475
va < 0
1476
va < 0
1484
vb <0
1486
va < 0
1487
va < 0
-1
376
vc < 0
581
vb <0
775
vb <0
853
vb <0
860
vb <0
861
va < 0
861
va < 0
915
vb <0
1267
va < 0
1410
va < 0
1420
va < 0
1494
va < 0
-1
987
vc < 0
1238
vc < 0
-1
349
vc < 0
1309
vb <0
-1
175
vd < 0
350
vb <0
937
va < 0
1019
vb <0
1341
va < 0
1406
vc < 0
-1
21
vb <0
133
vb <0
139
vc < 0
142
vb <0
294
vd < 0
331
vb <0
522
vd < 0
583
va < 0
670
vb <0
715
va < 0
802
vb <0
897
va < 0
953
vb <0
995
va < 0
1108
va < 0
1206
vd < 0
1321
vb <0
-1
101
va < 0
209
va < 0
275
va < 0
510
va < 0
561
va < 0
589
vb <0
975
vb <0
1207
va < 0
1210
va < 0
-1
132
va < 0
271
vb <0
-1
212

692
vb <0
695
va < 0
696
va < 0
1373
va < 0
1413
va < 0
1414
vb <0
1489
vb <0
1491
va < 0
-1
510
va < 0
646
vb <0
975
vb <0
1125
va < 0
-1
145
vb <0
264
va < 0
286
vb <0
296
vc < 0
353
va < 0
426
vb <0
539
va < 0
892
va < 0
1128
vb <0
1184
vb <0
-1
10
vc < 0
14
vb <0
204
va < 0
245
vb <0
376
vb <0
503
vb <0
518
va < 0
714
va < 0
776
vb <0
982
va < 0
1059
va < 0
1265
va < 0
-1
1208
vb <0
-1
115
va < 0
629
vb <0
791
vc < 0
847
va < 0
883
va < 0
913
922
va < 0
1010
va < 0
1111
va < 0
1169
va < 0
1229
vd < 0
1468
va < 0
-1
352
vd < 0
-1
438
va < 0
439
vb <0
848
va < 0
907
va < 0
1092
va < 0
1226
va < 0
1460
va < 0
1463
va < 0
-1
15
va < 0
106
vb <0
147
vb <0
167
va < 0
167
va < 0
237
va < 0
401
vb <0
445
va < 0
696
va < 0
1266
vb <0
1373
va < 0
1489
va < 0
1491
vc < 0
1493
vc < 0
-1
527
va < 0
1370
vb <0
-1
903
vb <0
-1
119
vb <0
395
va < 0
889
vd < 0
939
va < 0
1028
vd < 0
1312
vc < 0
1346
vb <0
1450
vd < 0
-1
902
va < 0
-1
144
vb <0
188
va < 0
193
va < 0
276
vb <0
465
va < 0
734
vc < 0
9

237
vb <0
-1
437
-1
188
vb <0
333
va < 0
433
vb <0
446
va < 0
448
vb <0
729
va < 0
879
vb <0
978
va < 0
1037
vc < 0
1039
vd < 0
1101
vc < 0
1162
va < 0
1314
va < 0
1339
vc < 0
1428
va < 0
1429
va < 0
-1
111
vb <0
374
vb <0
377
va < 0
511
vb <0
685
va < 0
1047
va < 0
1152
va < 0
-1
294
vb <0
299
va < 0
675
vc < 0
678
va < 0
987
vc < 0
996
vb <0
1050
va < 0
1156
vc < 0
1237
va < 0
1473
vb <0
-1
51
vb <0
636
vb <0
1190
va < 0
1382
va < 0
1386
vc < 0
1445
va < 0
-1
75
va < 0
124
vc < 0
352
vd < 0
437
vd < 0
466
vc < 0
479
vc < 0
515
vc < 0
515
vc < 0
567
vb <0
737
vb <0
744
vb <0
789
va < 0
875
vb <0
905
va < 0
926
va < 0
927
vb <0
948
vb <0
973
vb <0
994
vc < 0
1034
va < 0
1035
vc < 0
1129
va < 0
1257
vb <0
1284
va < 0
1285
va < 0
1286
vb <0
1289
va < 0
1290
va < 0
-1
238
-1
26
va < 0
480
va < 0
575
va < 0
-1
56
va < 0
56
va < 0
57
va < 0
370
va < 0
-1
994
-1
269
va < 0
680
va < 0
1442
va < 0
1446
va < 0
1487
vb <0
-1
119
vb <0
458
va < 0
838
va < 0
1009
vd < 0
1014
vd < 0
1028
vc < 0
126

va < 0
285
vc < 0
311
va < 0
317
va < 0
380
vc < 0
428
vb <0
672
va < 0
808
vb <0
843
vc < 0
1017
va < 0
1068
vb <0
-1
19
va < 0
219
va < 0
316
vb <0
579
vd < 0
1033
va < 0
1062
va < 0
1114
vb <0
1175
vb <0
1180
va < 0
1344
va < 0
1347
va < 0
-1
238
va < 0
255
va < 0
366
vb <0
417
va < 0
453
va < 0
534
va < 0
-1
61
va < 0
163
vc < 0
392
va < 0
454
va < 0
756
vb <0
895
vd < 0
967
vc < 0
1055
vb <0
-1
203
va < 0
1318
va < 0
-1
4
vb <0
362
va < 0
432
va < 0
624
vb <0
705
va < 0
706
va < 0
751
vb <0
751
vb <0
754
va < 0
-1
704
vb <0
813
vb <0
815
va < 0
1113
vc < 0
-1
80
va < 0
176
vd < 0
346
va < 0
392
va < 0
483
va < 0
598
vb <0
740
va < 0
974
vb <0
1002
va < 0
1003
vc < 0
1004
vb <0
1119
vc < 0
1172
vb <0
1246
vb <0
1424
vb <0
-1
4
vb <0
272
vb <0
429
va < 0
611
vb <0
624
vb <0
671
vc < 0
697
va < 0
705
va < 0
706
va < 0
751
vb <0
751
vb <0
754
vb <0
896
vb <0
1112
va < 0
1220
va < 0
1227
vb <0
1228
va < 0
-1
99
va < 0
232
va < 0
318
va < 0
558
va < 0
587
vb <0
758
vb <0
883
984
va < 0


vb <0
894
va < 0
918
vb <0
960
vb <0
1063
va < 0
1075
va < 0
1107
va < 0
1263
va < 0
1269
va < 0
1272
vb <0
1466
va < 0
1468
va < 0
-1
541
va < 0
624
vb <0
731
va < 0
864
vb <0
893
vb <0
981
vd < 0
1008
va < 0
1098
va < 0
1222
va < 0
-1
104
va < 0
117
va < 0
148
va < 0
172
va < 0
230
vb <0
434
va < 0
491
vd < 0
522
vb <0
631
vb <0
720
va < 0
772
va < 0
802
va < 0
814
va < 0
866
va < 0
950
va < 0
994
va < 0
1124
vb <0
1128
va < 0
1199
vc < 0
1200
vb <0
1201
va < 0
1205
va < 0
1210
va < 0
1287
vc < 0
1288
vc < 0
-1
180
va < 0
444
va < 0
538
va < 0
668
vc < 0
836
vb <0
931
va < 0
1041
va < 0
1281
va < 0
1292
vb <0
-1
142
va < 0
294
vb <0
1082
vb <0
-1
263
va < 0
534
vd < 0
746
vc < 0
951
vb <0
1027
vb <0
1065
vb <0
1069
va < 0
1345
va < 0
1384
va < 0
-1
1275
vd < 0
-1
1407
vb <0
-1
143
va < 0
158
va < 0
328
vd < 0
384
va < 0
854
va < 0
1150
va < 0
1181
va < 0
1477
va < 0
1482
va < 0
-1
1027
vb <0
1030
vb <0
1114
vb <0
1191
vc < 0
1212
vb <0
1243
vb <0
1307
va < 0
1309
vb <0
1313
va < 0
13

vd < 0
1160
vc < 0
1162
1314
va < 0
-1
835
vb <0
-1
997
va < 0
-1
166
va < 0
400
va < 0
544
vb <0
656
va < 0
1213
vb <0
1215
va < 0
1365
vb <0
-1
2
vc < 0
157
va < 0
214
va < 0
406
va < 0
475
vc < 0
502
va < 0
782
va < 0
1104
vb <0
1138
vb <0
-1
581
vb <0
775
vb <0
860
vb <0
861
va < 0
861
va < 0
-1
81
va < 0
256
vb <0
263
va < 0
746
vc < 0
834
vc < 0
886
vb <0
951
vb <0
1027
vb <0
1029
vc < 0
1065
vb <0
1114
vb <0
1167
vd < 0
1180
vb <0
1195
vb <0
1344
va < 0
1345
vc < 0
1384
vb <0
1391
vb <0
-1
26
va < 0
39
336
va < 0
352
va < 0
480
va < 0
567
vd < 0
575
va < 0
710
va < 0
744
va < 0
763
vb <0
924
va < 0
1174
vc < 0
1279
vb <0
1437
vc < 0
-1
48
va < 0
112
va < 0
174
vb <0
455
va < 0
632
va < 0
677
vb <0
-1
1036
vd < 0
-1
574
vc < 0
-1
163
vd < 0
182
va < 0
350
vb <0
366
va < 0
392
va < 0
501
va < 0
584
vb <0
756
va < 0
1080
va < 0
-1
35
vb <0
209
va < 0
231
vb <0
242
vd < 0
573
va < 0
635
vb <0
662
vb <0
919
va < 0
990
vb <0
1019
va < 0
1103
va < 0
1207
va < 0
-1
245
vb <0
322
vb <0
4

va < 0
400
vb <0
469
vc < 0
620
vb <0
780
va < 0
1155
vb <0
1242
va < 0
1294
va < 0
-1
6
vc < 0
81
vb <0
166
va < 0
323
va < 0
544
vb <0
780
va < 0
906
va < 0
1069
va < 0
1173
vc < 0
1213
va < 0
1215
vb <0
1365
vb <0
-1
0
vc < 0
28
va < 0
119
vb <0
125
vd < 0
333
va < 0
395
va < 0
433
vd < 0
440
va < 0
454
vb <0
729
va < 0
889
vb <0
983
vc < 0
1028
vd < 0
1037
va < 0
1039
vb <0
1237
vb <0
1252
vc < 0
1314
vc < 0
-1
56
va < 0
56
va < 0
57
va < 0
370
va < 0
-1
129
vc < 0
364
va < 0
842
va < 0
1254
vd < 0
1260
vb <0
1263
vb <0
1269
vc < 0
1270
va < 0
1272
vc < 0
1398
va < 0
1399
vb <0
-1
78
va < 0
485
vc < 0
597
vc < 0
605
va < 0
682
va < 0
816
vb <0
1059
va < 0
-1
237
vb <0
695
va < 0
-1
75
vb <0
124
vc < 0
240
vc < 0
274
vb <0
382
va < 0
408
va < 0
437
vb <0
468
vb <0
476
va < 0
484
vc < 0
491
vc < 0
604
va < 0
699
va < 0
711
va < 0
717
va < 0
737
va < 0
948
vc < 0
952
va < 0
973
vd < 0
1046
va < 0
1202
vb <0
1218
vb <0
1271
vb <0
1337
vb <0
-1
3
vb <0
143
vb <0
158
va < 0
432
vc < 0
50

361
vb <0
461
vd < 0
467
vb <0
472
vb <0
485
vb <0
493
va < 0
517
va < 0
543
vc < 0
563
va < 0
584
va < 0
591
vb <0
597
vc < 0
617
va < 0
619
vd < 0
682
va < 0
764
vc < 0
765
va < 0
846
vb <0
918
vb <0
1011
va < 0
1059
va < 0
1186
vb <0
1274
va < 0
1375
va < 0
1376
vb <0
-1
278
va < 0
898
va < 0
-1
61
va < 0
392
vb <0
674
vb <0
756
vd < 0
841
vb <0
1048
vc < 0
-1
95
va < 0
203
va < 0
310
va < 0
315
vb <0
569
va < 0
701
vb <0
703
vb <0
826
va < 0
1435
va < 0
1443
va < 0
1444
va < 0
1448
va < 0
1449
va < 0
1451
vb <0
1454
vb <0
-1
237
vb <0
1488
vb <0
-1
265
vb <0
600
vb <0
-1
8
va < 0
10
vc < 0
14
vb <0
191
vb <0
204
va < 0
361
va < 0
376
vb <0
493
vb <0
501
va < 0
503
vb <0
518
va < 0
543
vb <0
714
va < 0
776
vb <0
894
vb <0
918
va < 0
960
vc < 0
982
va < 0
1059
va < 0
1063
va < 0
1186
va < 0
1263
vb <0
1265
va < 0
1269
va < 0
1272
vb <0
-1
345
va < 0
359
vb <0
458
va < 0
1038
va < 0
1057
va < 0
1325
va < 0
-1
235
va < 0
657
vb <0
1147
vc < 0
-1
5
va < 0
59
va < 0
93
va < 0
116
vb <0
7

-1
52
va < 0
679
vb <0
769
va < 0
931
va < 0
1137
vb <0
1140
va < 0
-1
825
vb <0
-1
75
va < 0
124
vc < 0
240
va < 0
352
va < 0
382
vb <0
416
vd < 0
437
vd < 0
466
vb <0
567
vd < 0
615
va < 0
699
va < 0
737
va < 0
948
vd < 0
973
vb <0
994
vc < 0
1439
vc < 0
-1
93
va < 0
219
va < 0
785
va < 0
1438
va < 0
1448
va < 0
-1
38
va < 0
64
va < 0
110
vb <0
281
va < 0
390
vd < 0
457
vc < 0
464
va < 0
489
va < 0
545
va < 0
580
va < 0
593
va < 0
596
va < 0
734
vc < 0
770
vb <0
829
vb <0
916
vb <0
1027
vb <0
1048
vd < 0
1049
va < 0
1151
va < 0
1329
vb <0
1330
va < 0
1331
va < 0
1332
va < 0
1333
vb <0
-1
364
vb <0
842
va < 0
1260
va < 0
1272
vb <0
1398
va < 0
1399
va < 0
-1
685
va < 0
686
va < 0
-1
40
vb <0
218
vc < 0
287
vb <0
780
va < 0
781
vb <0
791
va < 0
1350
va < 0
1358
vb <0
-1
1106
vb <0
-1
99
va < 0
161
va < 0
161
va < 0
572
va < 0
757
va < 0
758
vb <0
1077
vc < 0
1131
vb <0
1469
vb <0
-1
1457
vc < 0
-1
71
va < 0
130
vb <0
191
va < 0
442
vb <0
477
va < 0
584
va < 0
761
vb <0
846
vb <0
882
va

va < 0
1313
va < 0
1350
va < 0
1358
va < 0
1363
vb <0
1369
va < 0
-1
21
vb <0
133
va < 0
139
va < 0
142
va < 0
294
va < 0
331
va < 0
375
va < 0
395
vb <0
471
vb <0
549
vb <0
583
va < 0
715
vb <0
903
vb <0
953
va < 0
995
vb <0
1108
va < 0
1206
vb <0
-1
106
va < 0
140
va < 0
147
va < 0
187
va < 0
195
va < 0
225
va < 0
288
va < 0
692
vb <0
695
va < 0
696
va < 0
750
va < 0
1090
va < 0
1367
va < 0
-1
244
vb <0
742
va < 0
919
vb <0
1044
va < 0
-1
180
va < 0
185
va < 0
333
vc < 0
380
va < 0
418
va < 0
433
va < 0
1101
vb <0
-1
733
va < 0
1204
va < 0
1209
vb <0
1400
va < 0
1401
va < 0
-1
18
va < 0
208
va < 0
222
va < 0
527
va < 0
679
va < 0
726
va < 0
766
va < 0
1137
va < 0
1370
vb <0
-1
39
vb <0
107
vb <0
201
vb <0
404
va < 0
466
va < 0
529
va < 0
578
vb <0
903
vb <0
995
vb <0
996
va < 0
1050
vb <0
1108
va < 0
-1
846
vc < 0
-1
81
va < 0
193
vb <0
464
vb <0
469
vc < 0
681
va < 0
1062
va < 0
1187
vb <0
1293
va < 0
1294
va < 0
1298
vb <0
1302
vb <0
1305
vb <0
1307
vb <0
1315
vb <0
1318
va < 0
133

1239
vc < 0
-1
236
vb <0
239
va < 0
391
va < 0
396
vb <0
452
va < 0
-1
40
vb <0
218
vc < 0
287
vb <0
780
va < 0
781
vb <0
791
va < 0
1350
va < 0
1358
va < 0
-1
81
va < 0
1030
vb <0
1065
vb <0
1307
va < 0
1309
vb <0
1313
va < 0
1354
va < 0
1357
va < 0
1374
vb <0
1384
vb <0
-1
46
vc < 0
290
vc < 0
307
va < 0
371
vc < 0
456
vc < 0
473
va < 0
552
vb <0
842
va < 0
932
vd < 0
969
va < 0
970
va < 0
998
va < 0
1032
va < 0
1216
vb <0
1251
vb <0
1254
va < 0
1256
va < 0
1258
vb <0
1260
va < 0
1278
vb <0
1281
va < 0
1295
vb <0
1296
vd < 0
1316
va < 0
1398
va < 0
1399
vb <0
1407
vb <0
-1
174
vb <0
227
va < 0
470
va < 0
712
va < 0
931
va < 0
1106
vb <0
1132
vb <0
-1
296
303
vc < 0
363
vb <0
515
va < 0
515
va < 0
631
va < 0
789
va < 0
875
va < 0
905
vc < 0
926
vb <0
927
va < 0
948
vb <0
973
vb <0
994
va < 0
1035
va < 0
1124
vc < 0
1129
vb <0
1208
va < 0
1284
vb <0
1285
vc < 0
1286
va < 0
1289
va < 0
1290
vb <0
-1
28
va < 0
50
vd < 0
125
va < 0
144
vb <0
188
va < 0
197
vc < 0
276
vb <0
330
va < 0
333


492
va < 0
502
vb <0
600
va < 0
782
vb <0
-1
704
vb <0
813
vb <0
815
va < 0
1113
vc < 0
-1
111
vb <0
374
va < 0
685
va < 0
-1
39
-1
729
vc < 0
1071
va < 0
1134
vc < 0
-1
278
vb <0
384
va < 0
649
vb <0
733
va < 0
1328
va < 0
1401
va < 0
1404
va < 0
1474
va < 0
1480
va < 0
-1
45
va < 0
109
va < 0
273
va < 0
504
vb <0
618
vb <0
690
va < 0
790
vb <0
822
vb <0
824
va < 0
832
va < 0
891
vb <0
1042
va < 0
1095
va < 0
1267
va < 0
1268
va < 0
1275
va < 0
1282
va < 0
1494
va < 0
-1
355
vc < 0
509
va < 0
1266
vb <0
1489
va < 0
1493
vb <0
-1
8
va < 0
90
vd < 0
129
vb <0
383
va < 0
472
va < 0
889
vc < 0
960
vb <0
1105
va < 0
1107
va < 0
1169
vb <0
1214
va < 0
1270
vb <0
1465
va < 0
1467
vb <0
-1
302
vb <0
482
va < 0
857
va < 0
1361
vb <0
1363
vb <0
-1
18
va < 0
65
vb <0
208
va < 0
222
va < 0
400
vb <0
726
va < 0
766
va < 0
1016
va < 0
1130
vc < 0
1351
vb <0
1358
va < 0
1359
vc < 0
-1
164
va < 0
375
vc < 0
393
vc < 0
394
vd < 0
395
vd < 0
446
va < 0
666
vc < 0
862
vb <0
978
vb <0
1037
vc < 0
1039
vc

1135
va < 0
-1
903
vb <0
-1
80
va < 0
176
vd < 0
346
va < 0
392
va < 0
483
va < 0
598
vb <0
740
va < 0
974
vb <0
1002
va < 0
1003
vc < 0
1004
vb <0
1119
vc < 0
1172
vb <0
1246
vb <0
1424
vb <0
-1
91
vb <0
173
va < 0
-1
13
va < 0
115
vb <0
130
vb <0
137
va < 0
152
va < 0
166
va < 0
177
vc < 0
347
va < 0
360
va < 0
403
va < 0
477
va < 0
719
va < 0
786
vb <0
838
vd < 0
847
va < 0
877
vc < 0
881
vb <0
921
va < 0
967
vb <0
1010
vb <0
1071
va < 0
1100
va < 0
1217
va < 0
1468
va < 0
-1
104
-1
76
va < 0
620
vb <0
1155
vb <0
1350
va < 0
-1
17
vb <0
100
va < 0
206
va < 0
441
452
vb <0
482
vb <0
601
vb <0
610
vb <0
833
vb <0
833
vb <0
837
vb <0
855
va < 0
856
va < 0
856
va < 0
857
va < 0
858
vb <0
858
vb <0
859
vb <0
870
va < 0
1025
vd < 0
-1
15
va < 0
72
vb <0
204
va < 0
245
vb <0
401
va < 0
445
va < 0
714
va < 0
778
va < 0
779
vb <0
839
vb <0
-1
930
va < 0
1035
vc < 0
1286
vb <0
1325
va < 0
1439
vc < 0
1447
vb <0
-1
98
va < 0
660
vb <0
930
va < 0
1012
va < 0
1143
vc < 0
1277
va < 0
1280
vc < 0


-1
62
vc < 0
626
vb <0
1066
vb <0
1085
vc < 0
1465
va < 0
1467
vb <0
-1
301
-1
649
vb <0
898
vb <0
1183
va < 0
1403
va < 0
1440
va < 0
1441
vb <0
-1
11
vb <0
66
vb <0
91
vb <0
141
va < 0
223
va < 0
422
va < 0
536
vc < 0
707
va < 0
920
va < 0
957
va < 0
1001
vb <0
1035
vc < 0
1076
vc < 0
1091
vc < 0
1122
vb <0
1147
vc < 0
1286
vb <0
1395
vb <0
-1
384
-1
2
va < 0
157
vb <0
214
va < 0
475
va < 0
492
va < 0
502
va < 0
600
vb <0
782
vb <0
-1
1027
vb <0
1030
vb <0
1114
vb <0
1191
vc < 0
1212
vb <0
1243
vb <0
1307
va < 0
1309
va < 0
1313
va < 0
1354
va < 0
1357
va < 0
1374
vb <0
-1
71
vc < 0
563
va < 0
605
va < 0
867
vc < 0
-1
13
va < 0
130
vb <0
177
vb <0
240
va < 0
347
va < 0
746
vc < 0
877
vc < 0
881
vb <0
967
vb <0
1055
vb <0
1191
vb <0
-1
86
va < 0
90
vc < 0
182
va < 0
279
vb <0
350
vb <0
461
va < 0
472
va < 0
501
va < 0
547
vb <0
584
vb <0
604
va < 0
997
va < 0
1080
va < 0
1105
va < 0
1261
vd < 0
1270
va < 0
1271
vb <0
1274
vb <0
1283
va < 0
1306
vb <0
1375
va < 0
1405
vc < 0
1411
va < 

132
va < 0
271
vb <0
-1
400
va < 0
494
vb <0
620
vb <0
656
va < 0
780
va < 0
1155
vb <0
1310
va < 0
-1
439
vb <0
848
va < 0
893
vb <0
-1
145
vb <0
264
va < 0
286
vb <0
296
vb <0
353
va < 0
426
vb <0
539
va < 0
892
va < 0
1128
vb <0
1184
vb <0
-1
118
va < 0
188
vb <0
793
va < 0
845
va < 0
1101
vb <0
1339
va < 0
1428
va < 0
1429
va < 0
-1
3
vb <0
356
va < 0
513
vd < 0
611
vb <0
671
va < 0
697
vb <0
896
vb <0
1220
va < 0
1227
vb <0
1228
va < 0
1462
va < 0
-1
6
vc < 0
19
va < 0
193
vb <0
255
vb <0
454
va < 0
464
va < 0
469
vb <0
681
va < 0
895
vd < 0
906
va < 0
967
vb <0
1055
vb <0
1114
vb <0
1187
vb <0
1293
va < 0
1294
va < 0
1298
vb <0
1302
vb <0
1305
vb <0
1307
va < 0
1315
vb <0
1318
va < 0
1333
va < 0
1353
va < 0
1355
va < 0
1356
va < 0
1357
va < 0
-1
42
vb <0
277
va < 0
307
va < 0
371
vb <0
762
va < 0
842
va < 0
998
va < 0
1021
vc < 0
1193
va < 0
1251
vb <0
1256
vb <0
1258
vb <0
1260
vb <0
1281
va < 0
1398
va < 0
1399
vb <0
1407
vb <0
-1
316
vb <0
1033
va < 0
-1
25
vb <0
69
va < 0
94


1266
vb <0
-1
9
va < 0
118
va < 0
188
vb <0
227
va < 0
324
va < 0
344
va < 0
418
va < 0
470
va < 0
712
va < 0
793
va < 0
845
va < 0
956
va < 0
1136
va < 0
1139
va < 0
1425
va < 0
-1
292
va < 0
-1
301
va < 0
-1
385
va < 0
629
va < 0
656
va < 0
725
vc < 0
921
va < 0
1352
vb <0
1365
vb <0
1371
va < 0
-1
937
va < 0
-1
52
vc < 0
128
va < 0
198
va < 0
455
va < 0
555
va < 0
639
vb <0
1196
va < 0
1197
vc < 0
1241
va < 0
-1
620
vb <0
1155
vb <0
-1
264
va < 0
459
va < 0
892
va < 0
1122
vb <0
1239
vc < 0
-1
66
va < 0
230
va < 0
252
vd < 0
422
va < 0
536
va < 0
866
va < 0
958
va < 0
1001
va < 0
1058
vb <0
1164
vb <0
1205
va < 0
1291
va < 0
-1
2
vc < 0
157
va < 0
214
va < 0
265
vb <0
406
va < 0
475
vc < 0
502
va < 0
546
va < 0
546
va < 0
648
va < 0
727
va < 0
782
va < 0
1036
vc < 0
1104
vb <0
1144
vb <0
-1
383
vb <0
1111
va < 0
1214
va < 0
1465
va < 0
-1
0
vc < 0
28
va < 0
119
vb <0
125
vb <0
333
va < 0
395
va < 0
433
vd < 0
440
va < 0
454
vb <0
729
va < 0
889
vb <0
983
vc < 0
1028
vd < 0
1037
va <

1137
va < 0
-1
554
vd < 0
1475
va < 0
-1
244
vb <0
662
vb <0
687
va < 0
823
va < 0
919
vb <0
990
va < 0
999
vb <0
1109
va < 0
1138
va < 0
1144
vd < 0
-1
47
vb <0
85
vb <0
254
va < 0
300
va < 0
309
vb <0
357
va < 0
357
va < 0
367
vb <0
373
va < 0
390
vd < 0
457
vc < 0
471
vb <0
476
va < 0
717
va < 0
770
vd < 0
784
va < 0
862
vc < 0
929
va < 0
945
vc < 0
1048
va < 0
1120
vb <0
1181
vc < 0
1321
vb <0
1322
vc < 0
1322
vc < 0
1337
vc < 0
1403
va < 0
1473
vb <0
1478
vb <0
-1
997
vb <0
-1
5
va < 0
59
va < 0
93
va < 0
111
vb <0
116
vb <0
374
va < 0
379
vb <0
686
vb <0
785
vb <0
1438
va < 0
-1
401
va < 0
778
va < 0
-1
233
va < 0
498
vb <0
609
vb <0
612
va < 0
700
va < 0
701
vb <0
702
vb <0
703
vb <0
1435
va < 0
-1
94
va < 0
130
va < 0
191
vb <0
322
vb <0
477
vb <0
501
va < 0
882
vc < 0
1186
va < 0
1266
vb <0
-1
101
va < 0
209
va < 0
275
va < 0
510
va < 0
561
va < 0
589
vb <0
975
vb <0
1207
va < 0
1210
va < 0
-1
238
va < 0
255
va < 0
407
va < 0
484
va < 0
939
va < 0
1046
vb <0
1202
vc < 0
1320
v

va < 0
696
va < 0
1266
vb <0
1373
va < 0
1489
va < 0
1491
va < 0
1493
vb <0
-1
1305
va < 0
-1
363
va < 0
434
va < 0
720
va < 0
789
vd < 0
865
vc < 0
875
vb <0
905
vb <0
927
vc < 0
1199
vb <0
1200
vb <0
1208
va < 0
1290
va < 0
-1
98
va < 0
261
va < 0
982
vc < 0
1277
va < 0
1280
va < 0
1405
vb <0
1417
vb <0
-1
76
va < 0
620
vb <0
1155
vb <0
1350
va < 0
-1
640
va < 0
-1
16
vb <0
36
vc < 0
60
vb <0
88
vb <0
137
va < 0
420
va < 0
496
vb <0
716
va < 0
716
va < 0
732
vb <0
786
vb <0
842
vc < 0
843
vb <0
877
vd < 0
881
vb <0
1115
va < 0
1142
va < 0
1254
vb <0
1260
va < 0
1399
va < 0
-1
132
va < 0
271
vb <0
-1
62
va < 0
345
va < 0
871
va < 0
1299
va < 0
-1
61
vd < 0
375
vb <0
394
va < 0
407
va < 0
476
va < 0
603
vb <0
615
vb <0
770
vd < 0
949
vb <0
1314
vc < 0
1337
vc < 0
-1
107
vb <0
126
vb <0
150
vb <0
168
vb <0
299
vc < 0
301
va < 0
402
vc < 0
440
vb <0
446
va < 0
578
vb <0
664
vb <0
665
va < 0
675
va < 0
678
vb <0
903
vb <0
917
va < 0
941
vc < 0
978
va < 0
987
va < 0
995
vb <0
996
va < 0
10

-1
123
vc < 0
572
va < 0
1233
vb <0
1362
vb <0
-1
1384
vb <0
-1
39
vc < 0
44
vb <0
352
va < 0
567
va < 0
710
va < 0
724
va < 0
794
vb <0
996
vc < 0
1050
-1
98
va < 0
148
va < 0
261
va < 0
434
va < 0
479
vb <0
720
va < 0
899
vc < 0
950
va < 0
1199
vc < 0
-1
35
vd < 0
53
vb <0
242
va < 0
260
va < 0
338
vc < 0
406
va < 0
510
va < 0
595
va < 0
818
vc < 0
888
va < 0
975
va < 0
1078
vb <0
1104
vb <0
1138
vb <0
-1
142
va < 0
296
vb <0
303
va < 0
363
va < 0
630
vb <0
787
va < 0
806
vb <0
1124
va < 0
-1
8
va < 0
94
vc < 0
115
vb <0
229
vb <0
259
va < 0
267
va < 0
318
vb <0
361
vb <0
481
va < 0
747
vb <0
847
va < 0
876
va < 0
894
vb <0
918
va < 0
960
vc < 0
1063
va < 0
1075
va < 0
1107
va < 0
1272
vb <0
1466
va < 0
1468
va < 0
-1
87
va < 0
1305
va < 0
1315
vb <0
1318
va < 0
1356
va < 0
1374
vb <0
-1
87
va < 0
385
vb <0
728
va < 0
1158
vc < 0
1352
va < 0
1356
va < 0
1361
vb <0
1365
vc < 0
1371
va < 0
1374
va < 0
-1
129
vc < 0
364
va < 0
842
va < 0
1254
vd < 0
1260
vb <0
1263
vb <0
1269
vc < 0
127

vc < 0
1121
vb <0
1151
va < 0
1152
vb <0
1319
vc < 0
1434
va < 0
1435
va < 0
1436
va < 0
1438
vc < 0
1440
va < 0
1441
vd < 0
1443
vb <0
1444
va < 0
1446
va < 0
1449
va < 0
1451
vb <0
1454
vb <0
1483
va < 0
-1
42
vb <0
634
vb <0
1009
vd < 0
1021
vb <0
1193
vd < 0
1255
va < 0
-1
335
vc < 0
346
va < 0
477
va < 0
1003
vc < 0
1086
vb <0
1119
vc < 0
1146
va < 0
1377
vc < 0
1406
vc < 0
1423
vb <0
-1
48
vb <0
538
va < 0
570
vc < 0
1041
va < 0
-1
96
va < 0
126
vb <0
146
vb <0
197
va < 0
299
vc < 0
301
va < 0
402
vb <0
429
va < 0
440
vb <0
446
vc < 0
654
va < 0
664
va < 0
731
vb <0
848
va < 0
941
vc < 0
942
vb <0
978
va < 0
981
vd < 0
1007
va < 0
1018
va < 0
1022
va < 0
1083
vc < 0
1087
va < 0
1088
vc < 0
1097
va < 0
1112
va < 0
1156
vb <0
1157
vb <0
1226
va < 0
1230
va < 0
1238
vb <0
1336
vb <0
1340
vb <0
1342
vb <0
1349
va < 0
1381
vc < 0
1392
va < 0
1426
vc < 0
1430
vb <0
1433
vb <0
1460
va < 0
1463
va < 0
-1
1189
va < 0
1194
va < 0
1311
va < 0
1335
va < 0
-1
202
va < 0
336
va < 0
355
vc < 0


va < 0
596
va < 0
734
vc < 0
753
va < 0
792
va < 0
956
va < 0
1026
va < 0
1330
vb <0
1338
vb <0
-1
89
vd < 0
164
vc < 0
356
va < 0
411
va < 0
520
vd < 0
536
va < 0
666
va < 0
862
vb <0
929
vc < 0
949
vb <0
1162
vb <0
1327
vb <0
1389
va < 0
1462
va < 0
-1
20
va < 0
74
va < 0
92
va < 0
599
vb <0
652
vb <0
673
va < 0
759
va < 0
798
va < 0
933
vb <0
-1
184
vc < 0
299
va < 0
419
va < 0
421
va < 0
1156
va < 0
1326
va < 0
1459
va < 0
1473
vb <0
1478
vb <0
-1
65
vb <0
77
va < 0
656
va < 0
781
va < 0
921
va < 0
1071
va < 0
1130
vc < 0
1351
vb <0
1359
vc < 0
1366
va < 0
1370
vb <0
-1
278
vb <0
384
va < 0
649
vb <0
733
va < 0
1328
va < 0
1401
va < 0
1404
va < 0
1474
va < 0
1480
va < 0
-1
20
vb <0
74
va < 0
320
va < 0
378
va < 0
709
vb <0
759
vb <0
799
va < 0
801
va < 0
-1
80
vc < 0
155
vc < 0
177
vb <0
304
vb <0
472
va < 0
517
vb <0
619
va < 0
1073
va < 0
1154
va < 0
1344
va < 0
1345
vb <0
1379
vb <0
-1
551
vb <0
773
va < 0
987
vc < 0
1238
va < 0
-1
1073
-1
1383
va < 0
-1
129
vc < 0
710
va < 0
72

vb <0
843
vc < 0
989
vc < 0
1028
vb <0
1057
va < 0
1160
vc < 0
1252
va < 0
1254
va < 0
1295
vb <0
-1
124
vc < 0
261
va < 0
274
vb <0
279
vb <0
437
va < 0
501
vd < 0
518
va < 0
604
va < 0
737
va < 0
982
vc < 0
1034
va < 0
1269
vc < 0
1271
vb <0
1306
vb <0
-1
1122
vb <0
1239
vc < 0
-1
98
va < 0
508
va < 0
660
va < 0
930
va < 0
992
va < 0
1012
va < 0
1143
vb <0
1325
va < 0
-1
285
va < 0
358
va < 0
688
va < 0
-1
1073
vb <0
-1
592
vb <0
1471
va < 0
-1
438
va < 0
439
vb <0
848
va < 0
907
va < 0
1092
va < 0
1226
va < 0
1460
va < 0
1463
va < 0
-1
35
va < 0
53
va < 0
209
vb <0
242
vb <0
257
va < 0
339
va < 0
462
va < 0
687
va < 0
818
vb <0
823
vb <0
880
va < 0
962
va < 0
1070
vd < 0
1116
vd < 0
1118
va < 0
1127
va < 0
1138
va < 0
-1
949
vc < 0
-1
1036
vd < 0
-1
201
vb <0
903
vb <0
1082
vb <0
-1
12
va < 0
76
va < 0
207
vb <0
311
vb <0
320
va < 0
329
vb <0
378
va < 0
1015
vb <0
1133
va < 0
1159
vb <0
-1
151
vc < 0
337
vb <0
416
va < 0
954
vb <0
1168
vb <0
1240
vb <0
-1
144
vb <0
188
va < 0
276
vb

1264
vc < 0
1295
va < 0
1312
vc < 0
1450
va < 0
-1
1
vb <0
63
vc < 0
212
vb <0
266
va < 0
940
vb <0
940
vb <0
1249
vb <0
1416
vb <0
-1
122
va < 0
313
va < 0
574
vb <0
718
va < 0
1126
va < 0
1144
vd < 0
-1
4
vb <0
611
vb <0
624
vb <0
671
vb <0
697
vc < 0
705
va < 0
706
va < 0
751
vb <0
751
vb <0
754
va < 0
896
vb <0
1220
va < 0
1227
vb <0
1228
va < 0
-1
317
-1
28
va < 0
50
va < 0
554
vb <0
983
vc < 0
1187
va < 0
1318
va < 0
1331
va < 0
1334
va < 0
1475
va < 0
-1
12
va < 0
149
vb <0
317
va < 0
351
vb <0
414
vb <0
651
va < 0
800
vb <0
804
vb <0
805
vb <0
851
va < 0
-1
98
va < 0
660
va < 0
930
va < 0
1012
va < 0
1143
vc < 0
1277
va < 0
1280
vc < 0
-1
314
vb <0
630
vb <0
1122
vb <0
-1
129
vc < 0
251
vb <0
336
va < 0
355
vc < 0
479
vd < 0
509
va < 0
710
va < 0
763
va < 0
776
vb <0
1174
vc < 0
1185
va < 0
1257
vb <0
1263
vb <0
1273
va < 0
1279
vb <0
1297
va < 0
1396
va < 0
1411
va < 0
1437
vc < 0
1492
va < 0
-1
5
vb <0
134
vb <0
377
va < 0
592
vb <0
1484
vb <0
1486
va < 0
-1
363
va < 0
434
va

va < 0
61
vc < 0
121
vb <0
234
vc < 0
238
va < 0
290
vd < 0
347
vb <0
435
va < 0
556
vc < 0
603
vb <0
615
vb <0
955
vb <0
1032
vc < 0
1102
vb <0
1105
vd < 0
1216
vb <0
1261
va < 0
1347
vb <0
1453
vb <0
-1
574
-1
13
va < 0
61
vc < 0
121
vb <0
234
vc < 0
238
va < 0
290
vc < 0
347
vb <0
435
va < 0
556
vc < 0
603
vb <0
615
vb <0
955
vb <0
1032
vc < 0
1102
vb <0
1105
vd < 0
1216
vb <0
1261
va < 0
1347
vb <0
1453
vd < 0
-1
21
vc < 0
41
vb <0
331
va < 0
375
vd < 0
393
vd < 0
395
vd < 0
404
vc < 0
526
vb <0
549
vd < 0
583
va < 0
590
vb <0
953
vc < 0
1096
vb <0
-1
398
va < 0
-1
8
va < 0
383
va < 0
876
va < 0
960
vc < 0
1014
vc < 0
1107
va < 0
1169
vb <0
1214
va < 0
1465
va < 0
1467
va < 0
-1
76
va < 0
-1
18
va < 0
131
va < 0
207
vb <0
262
vb <0
329
vb <0
725
vc < 0
726
va < 0
735
vb <0
766
va < 0
774
vb <0
-1
58
va < 0
415
va < 0
447
va < 0
629
va < 0
771
vc < 0
781
va < 0
913
vb <0
922
va < 0
936
va < 0
1158
va < 0
1351
va < 0
1359
vb <0
1366
vc < 0
1370
va < 0
-1
62
va < 0
345
va < 0
458
va <

va < 0
1247
va < 0
1261
va < 0
1271
vc < 0
1344
vc < 0
1347
vb <0
-1
277
va < 0
319
va < 0
342
vb <0
512
va < 0
688
vc < 0
1300
vb <0
-1
516
va < 0
599
va < 0
638
vb <0
673
va < 0
-1
46
vc < 0
277
va < 0
762
va < 0
1278
vb <0
-1
314
va < 0
630
vb <0
678
va < 0
-1
17
va < 0
391
vb <0
396
vb <0
602
va < 0
1025
va < 0
1371
va < 0
-1
20
va < 0
73
vb <0
74
va < 0
108
va < 0
505
va < 0
651
va < 0
759
va < 0
798
va < 0
799
vb <0
800
vb <0
801
va < 0
803
vc < 0
-1
81
va < 0
218
vc < 0
232
vb <0
263
vd < 0
283
vb <0
287
vb <0
587
vb <0
771
va < 0
780
va < 0
868
886
vc < 0
951
va < 0
1010
va < 0
1065
vb <0
1173
va < 0
1366
va < 0
-1
42
vb <0
119
va < 0
192
vb <0
241
va < 0
359
vb <0
430
va < 0
458
va < 0
710
va < 0
777
vc < 0
1009
vb <0
1021
vb <0
1160
vc < 0
1193
va < 0
1264
vd < 0
1450
va < 0
-1
48
va < 0
112
va < 0
118
va < 0
174
vb <0
227
va < 0
258
va < 0
455
vc < 0
470
va < 0
632
vc < 0
677
vc < 0
712
va < 0
793
va < 0
845
va < 0
-1
156
vb <0
404
va < 0
995
vb <0
1082
va < 0
1108
vb <0
-1


vb <0
290
vc < 0
347
vb <0
435
va < 0
454
vb <0
556
vc < 0
603
vb <0
615
vb <0
1032
vc < 0
1216
vb <0
-1
180
va < 0
444
va < 0
538
va < 0
668
vc < 0
836
vb <0
931
va < 0
1041
va < 0
1281
va < 0
1292
vb <0
-1
503
-1
59
va < 0
116
vb <0
127
va < 0
153
va < 0
183
va < 0
297
va < 0
309
va < 0
389
vd < 0
495
vb <0
498
vb <0
612
vb <0
1047
va < 0
1120
vb <0
1152
va < 0
1319
va < 0
1434
va < 0
1435
vb <0
1436
va < 0
1438
va < 0
1440
va < 0
1441
vb <0
1451
va < 0
1454
vb <0
-1
278
va < 0
674
vb <0
802
va < 0
898
vb <0
1145
va < 0
1328
va < 0
1400
va < 0
1403
va < 0
-1
20
vb <0
185
va < 0
324
va < 0
344
va < 0
709
vb <0
759
va < 0
799
va < 0
1139
va < 0
-1
25
vb <0
69
vb <0
121
vb <0
190
va < 0
234
vb <0
435
va < 0
537
vb <0
556
vc < 0
634
vb <0
777
vc < 0
819
vd < 0
932
vc < 0
1089
va < 0
1102
va < 0
1255
va < 0
1264
vd < 0
1281
va < 0
-1
264
va < 0
459
va < 0
892
va < 0
-1
110
va < 0
134
va < 0
429
vb <0
446
va < 0
448
vb <0
666
vc < 0
862
va < 0
978
vb <0
1037
vc < 0
1039
vd < 0
1112
vb <0
1

va < 0
1452
va < 0
1482
vb <0
-1
152
va < 0
229
vb <0
232
vb <0
267
va < 0
318
vb <0
403
va < 0
481
va < 0
544
va < 0
667
va < 0
747
vc < 0
797
va < 0
959
va < 0
984
vb <0
1075
va < 0
1085
va < 0
1100
va < 0
1107
va < 0
1217
va < 0
1466
va < 0
-1
125
vc < 0
193
vb <0
281
va < 0
469
vb <0
494
vb <0
629
va < 0
656
va < 0
1055
vb <0
1163
va < 0
1163
va < 0
1242
va < 0
1294
va < 0
-1
1187
va < 0
1318
va < 0
1331
va < 0
1334
va < 0
1383
va < 0
-1
52
va < 0
128
vc < 0
198
va < 0
555
va < 0
560
vb <0
964
va < 0
1197
vb <0
1343
vc < 0
-1
51
va < 0
-1
237
vb <0
1488
vb <0
-1
13
va < 0
130
vb <0
177
vc < 0
240
va < 0
347
va < 0
746
vc < 0
877
vc < 0
881
vb <0
967
vb <0
1055
vb <0
1191
vb <0
-1
342
vb <0
355
vc < 0
371
vb <0
388
vb <0
509
va < 0
1056
vc < 0
1299
va < 0
1408
vc < 0
1415
va < 0
1489
vb <0
-1
50
vb <0
197
vc < 0
305
va < 0
-1
237
va < 0
695
va < 0
1490
va < 0
-1
8
va < 0
14
vb <0
90
vc < 0
103
va < 0
129
vc < 0
182
va < 0
376
vc < 0
383
va < 0
461
va < 0
472
va < 0
485
va < 0
501
va

vb <0
1231
vb <0
1262
va < 0
1313
va < 0
1362
vc < 0
1363
vb <0
1369
va < 0
-1
81
va < 0
287
vb <0
447
vc < 0
460
va < 0
532
vd < 0
780
va < 0
1030
vb <0
1065
vc < 0
1158
va < 0
1307
va < 0
1351
vb <0
1354
va < 0
1357
va < 0
1359
vb <0
1361
vc < 0
1364
vb <0
1374
vb <0
-1
187
va < 0
225
va < 0
372
vb <0
692
vb <0
695
va < 0
696
va < 0
1373
va < 0
1413
va < 0
1414
va < 0
1489
vb <0
1491
va < 0
-1
42
va < 0
241
va < 0
430
va < 0
450
va < 0
710
vb <0
777
vc < 0
1009
vb <0
1021
va < 0
1038
va < 0
1193
va < 0
1264
vb <0
1277
va < 0
1450
va < 0
1488
vb <0
-1
102
va < 0
202
va < 0
340
vc < 0
480
va < 0
575
vb <0
608
vc < 0
788
vb <0
831
va < 0
924
vb <0
1043
va < 0
1072
va < 0
1166
vb <0
1447
va < 0
-1
379
vb <0
398
va < 0
-1
79
va < 0
136
va < 0
295
va < 0
397
va < 0
412
vb <0
568
va < 0
568
va < 0
581
vb <0
582
vb <0
605
va < 0
606
va < 0
669
vb <0
669
vb <0
748
vb <0
909
vb <0
910
vb <0
910
vb <0
911
va < 0
912
va < 0
-1
54
va < 0
149
va < 0
194
va < 0
351
vb <0
414
va < 0
651
va < 0
672
v

577
va < 0
639
vb <0
645
va < 0
684
va < 0
773
va < 0
783
vb <0
934
va < 0
1064
vb <0
-1
292
vb <0
-1
455
vb <0
1196
vc < 0
1241
vb <0
1342
vb <0
1430
vb <0
1431
va < 0
-1
148
va < 0
279
vb <0
604
va < 0
662
vb <0
721
vc < 0
865
vc < 0
935
vd < 0
997
vb <0
1044
va < 0
1060
vc < 0
1061
va < 0
1080
va < 0
1247
va < 0
1261
va < 0
1271
vc < 0
1306
vb <0
-1
190
va < 0
417
va < 0
923
vc < 0
930
va < 0
1051
vd < 0
1057
va < 0
1084
vb <0
1143
vb <0
1453
va < 0
-1
61
va < 0
86
va < 0
90
vc < 0
238
va < 0
472
va < 0
604
va < 0
997
va < 0
1105
va < 0
1261
vd < 0
1270
va < 0
1271
vb <0
1344
vb <0
1347
va < 0
-1
10
vb <0
72
vc < 0
204
vc < 0
234
va < 0
450
va < 0
634
vb <0
714
vb <0
839
va < 0
894
vc < 0
982
vc < 0
1063
va < 0
1102
vc < 0
1105
vd < 0
1264
vc < 0
1280
va < 0
1405
va < 0
1417
vb <0
-1
263
va < 0
423
vc < 0
559
va < 0
951
vb <0
1002
vb <0
1153
va < 0
1167
vd < 0
1180
vb <0
1195
vb <0
1470
vb <0
-1
135
va < 0
250
va < 0
499
va < 0
576
vb <0
-1
1407
-1
15
va < 0
106
vb <0
147
vb <0
167


In [161]:
print(mask2)

(array([  -1,   -1,   -1, ...,  134, 1291,   -1]), array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       ...,
       [0.05885953, 0.29844447, 0.18160339, 0.46109261],
       [0.11787258, 0.20210807, 0.67307694, 0.0069424 ],
       [0.        , 0.        , 0.        , 0.        ]]))


In [15]:
aabbindx = mesh2.pos_to_aabb_index(points)
mesh2.aabb[314,:]

array([ 747, 1100,   -1, ...,   -1,   -1,   -1])

In [19]:
mesh2.nodes[mesh2.tetra[1100]]

array([[0.40625   , 0.        , 0.2578125 ],
       [0.36230469, 0.        , 0.4140625 ],
       [0.50612419, 0.        , 0.35839043],
       [0.48026525, 0.21744951, 0.35090743]])

In [18]:
points[0,:]

array([0.44240712, 0.17424164, 0.31584794])

In [ ]:
points = mesh2.nodes[mesh2.tetra]
print(points.shape)

vab = points[ :, 1, :] - points[ :, 0, :]
vac = points[ :, 2, :] - points[ :, 0, :]
vad = points[ :, 3, :] - points[ :, 0, :]
v = np.einsum('ij, ij->i', vab, np.cross(vac, vad, axisa=1, axisb=1)) / 6.
plt.hist(v)

In [ ]:
mesh2.step[0]*mesh2.step[1]*mesh2.step[2]

In [ ]:
#%%snakeviz
mask = mesh2.get_tetra2(points)#np.random.random((100,3)))


In [ ]:
print(np.sum(mask2[0] < 0))

In [ ]:
points[mask2 == -1]

In [ ]:
np.sum(mask[0] == -1)

In [ ]:
from LoopStructural.supports.tet_mesh import TetMesh

In [ ]:
mesh = TetMesh()
mesh.setup_mesh(np.array([[0,0,0],[1,1,1]]),n_tetra=3000)

In [ ]:
mesh.elements_for_array(points)

In [8]:
xi = 8
yi = 8
zi = 8
nx=9
ny=9
nz=9

In [9]:
global_index = xi+yi*nx+zi*nx*ny

In [10]:
print(global_index)

728


In [11]:
9*9*9

729

In [ ]:
9*9*9