In [80]:
%load_ext cython
import matplotlib.pyplot as plt

The cython extension is already loaded. To reload it, use:
  %reload_ext cython


In [2]:
import logging

import meshpy.tet
import numpy as np
from LoopStructural.cython.dsi_helper import cg
from numpy import linalg as la
from scipy.spatial import cKDTree
from sklearn.decomposition import PCA

logger = logging.getLogger(__name__)


class TetMesh:
    """
    A class containing the geometry of a tetrahedral mesh.
    Nodes are the vertices
    Elements are the tetrahedrons
    Neighbours are the neighbours
    Vertex properties are stored as a dict of np arrrays self.properties
    Element properties are self.property_gradients 
    """

    def __init__(self, **kwargs):
        """
        Creates a mesh object. This just assigns the mesh a name and a
        location to save

        """
        self.name = 'TetMesh'
        self.path = './'
        self.usetetgen = True
        self.save_mesh = False
        if 'name' in kwargs:
            self.name = kwargs['name']
        if 'path' in kwargs:
            self.path = kwargs['path']
        if 'tetgen' in kwargs:
            self.usetetgen = kwargs['tetgen']
        if 'save' in kwargs:
            self.save_mesh = kwargs['save']
        self.mesh = None
        self.shared_idxs = np.zeros(3, dtype=np.int)
        self.dinfo = {}
        self.cg_calculated = {}
        self.properties = {}
        self.property_gradients = {}
        self.property_gradients_nodes = {}
        self.element_gradients = {}
        self.element_nodes_to_id = {}
        self.regions = {}
        self.points = None
        self.surfaces = {}

    def setup_mesh(self, boundary_points, **kwargs):
        """
        Build a mesh given the boundary points
        Can define the resolution of the mesh using the kwargs
         
        n_tetra: number of tetrahedron
        maxvol: maximum volume for a single tetra - if both are specified
        this one is used.
        """
        self.pca = PCA(n_components=3)
        minx = boundary_points[0, 0]
        miny = boundary_points[0, 1]
        minz = boundary_points[0, 2]
        maxx = boundary_points[1, 0]
        maxy = boundary_points[1, 1]
        maxz = boundary_points[1, 2]
        points = np.array([
            (minx, miny, minz),
            (maxx, miny, minz),
            (maxx, maxy, minz),
            (minx, maxy, minz),
            (minx, miny, maxz),
            (maxx, miny, maxz),
            (maxx, maxy, maxz),
            (minx, maxy, maxz)
        ])
        self.surfaces['top'] = (
            (minx, miny, maxz), (maxx, miny, maxz), (maxx, maxy, maxz),
            (minx, maxy, maxz))
        self.surfaces['bottom'] = (
            (minx, miny, minz), (maxx, miny, minz), (maxx, maxy, minz),
            (minx, maxy, minz))

        self.points = points
        # calculate the 3 principal components to find the local coordinate
        # system
        self.pca.fit(points)
        # project the points into this coordinate system
        newp = self.pca.transform(points)
        n_tetra = 4000  # maxvol=0.001
        if 'n_tetra' in kwargs:
            n_tetra = kwargs['n_tetra']
        # calculate the volume of the bounding box
        maxvol = 0.001
        if 'maxvol' not in kwargs:
            lengthU = maxx - minx
            lengthV = maxy - miny
            lengthW = maxz - minz
            boxVol = lengthU * lengthW * lengthV
            correction_factor = 1.91
            maxvol = correction_factor * boxVol / n_tetra
        if 'maxvol' in kwargs:
            maxvol = kwargs['maxvol']

        facets = [
            [0, 1, 2, 3],
            [4, 5, 6, 7],
            [0, 4, 5, 1],
            [1, 5, 6, 2],
            [2, 6, 7, 3],
            [3, 7, 4, 0]
        ]

        # create the mesh
        info = meshpy.tet.MeshInfo()
        # use the projected points to build the mesh
        info.set_points(newp)
        info.set_facets(facets)
        meshpy_mesh = meshpy.tet.build(info, max_volume=maxvol,
                                       options=meshpy.tet.Options('pqn'))
        self.nodes = self.pca.inverse_transform(np.array(meshpy_mesh.points))
        self.elements = np.array(meshpy_mesh.elements, dtype=np.int64)
        self.neighbours = np.array(meshpy_mesh.neighbors, dtype=np.int64)
        self.n_nodes = len(self.nodes)
        self.n_elements = len(self.elements)
        self.barycentre = np.sum(self.nodes[self.elements][:, :, :],
                                 axis=1) / 4.
        self.tree = cKDTree(self.barycentre)
        self.minx = minx  # np.min(newp[:,0])#minx
        self.miny = miny  # np.min(newp[:,1])#miny
        self.minz = minz  # np.min(newp[:,2])#minz
        self.maxx = maxx  # np.max(newp[:,0])#maxx
        self.maxy = maxy  # np.max(newp[:,1])#maxy
        self.maxz = maxz  # np.max(newp[:,2])#maxz

        self.minpc0 = np.min(newp[:, 0])
        self.maxpc0 = np.max(newp[:, 0])
        self.minpc1 = np.min(newp[:, 1])
        self.maxpc1 = np.max(newp[:, 1])
        self.minpc2 = np.min(newp[:, 2])
        self.maxpc2 = np.max(newp[:, 2])

        self.regions['everywhere'] = np.ones(self.n_nodes).astype(bool)

        # precalculate the gradient matrices for all elements to save time
        # later
        e = np.arange(self.n_elements)
        ps = self.nodes[self.elements[e]]
        m = np.array(
            [[(ps[:, 1, 0] - ps[:, 0, 0]), (ps[:, 1, 1] - ps[:, 0, 1]),
              (ps[:, 1, 2] - ps[:, 0, 2])],
             [(ps[:, 2, 0] - ps[:, 0, 0]), (ps[:, 2, 1] - ps[:, 0, 1]),
              (ps[:, 2, 2] - ps[:, 0, 2])],
             [(ps[:, 3, 0] - ps[:, 0, 0]), (ps[:, 3, 1] - ps[:, 0, 1]),
              (ps[:, 3, 2] - ps[:, 0, 2])]])
        I = np.array(
            [[-1., 1., 0., 0.],
             [-1., 0., 1., 0.],
             [-1., 0., 0., 1.]])
        m = np.swapaxes(m, 0, 2)
        self.element_gradients = la.inv(m)

        self.element_gradients = self.element_gradients.swapaxes(1, 2)
        self.element_gradients = self.element_gradients @ I

    def add_region(self, region, name):
        """
        Add a region mask to the mesh, will also add as a property to the mesh
        :param region: numpy array n_nodes
        :param name: string giving name of the region
        :return:
        """
        self.regions[name] = region
        self.properties['REGION_' + name] = region.astype(float)

    def update_property(self, name, value, save=True):
        """
        Updates or adds new property to the mesh
        :param name: string fi
        :param value:
        :param save:
        :return:
        """
        self.properties[name] = value
        grads = self.get_elements_gradients(np.arange(self.n_elements))
        props = self.properties[name][
            self.elements[np.arange(self.n_elements)]]
        grad = np.einsum('ikj,ij->ik', grads, props)
        self.property_gradients[name] = grad
        if self.save_mesh:
            self.save()

    def transfer_gradient_to_nodes(self, propertyname):
        """
        Copy gradient from elements to nodes
        Averages the gradient for the 4 surrounding tetra for each node
        :param propertyname: name of the property
        :return:
        """
        grad = np.zeros((self.nodes.shape[0], 3))
        for i, e in enumerate(self.elements):
            for n in e:
                grad[n, :] += self.property_gradients[propertyname][i, :]
        grad /= 4
        self.property_gradients_nodes[propertyname] = grad

    def calculate_constant_gradient(self, region):
        self.dinfo = np.zeros(self.n_elements).astype(bool)
        # add cg constraint for all of the
        EG = self.get_elements_gradients(np.arange(self.n_elements))
        region = region.astype('int64')
        idc, c, ncons = cg(EG, self.neighbours, self.elements, self.nodes,
                           region)
        idc = np.array(idc[:ncons, :])
        c = np.array(c[:ncons, :])
        B = np.zeros(c.shape[0])
        return c, idc, B

    def get_constant_gradient(self, w=0.1, region='everywhere', **kwargs):
        return self.calculate_constant_gradient(region, **kwargs)

    def get_elements_gradients(self, e):
        """
        Returns the gradient of the elements using their global index.
        Sped up using numpy
        """
        return self.element_gradients[e]

    def calc_bary_c(self, e, p):
        """
        Calculate the barycentre coordinates for an array of n elements 
        and n points
        """
        points = self.nodes[self.elements[e]]
        npts = len(e)
        vap = p - points[:, 0, :]
        vbp = p - points[:, 1, :]
        # vcp = p - points[:, 2, :]
        # vdp = p - points[:, 3, :]
        vab = points[:, 1, :] - points[:, 0, :]
        vac = points[:, 2, :] - points[:, 0, :]
        vad = points[:, 3, :] - points[:, 0, :]
        vbc = points[:, 2, :] - points[:, 1, :]
        vbd = points[:, 3, :] - points[:, 1, :]

        va = np.sum(vbp * np.cross(vbd, vbc, axisa=1, axisb=1), axis=1) / 6.
        vb = np.sum(vap * np.cross(vac, vad, axisa=1, axisb=1), axis=1) / 6.
        vc = np.sum(vap * np.cross(vad, vab, axisa=1, axisb=1), axis=1) / 6.
        vd = np.sum(vap * np.cross(vab, vac, axisa=1, axisb=1), axis=1) / 6.
        v = np.sum(vab * np.cross(vac, vad, axisa=1, axisb=1), axis=1) / 6.
        c = np.zeros((4, npts))
        c[0, :] = va / v
        c[1, :] = vb / v
        c[2, :] = vc / v
        c[3, :] = vd / v
        return c

    def elements_for_array(self, array, k=10):
        """
        Get the elements for an array of points
        :param array:
        :param k:
        :return:
        """
        # find the nearest k elements for the arrays
        # reducing k could speed up calculation but migh add errors

        d, ee = self.tree.query(array)

        inside = np.zeros(array.shape[0]).astype(bool)
        inside[:] = True
        # inside = iarray[:, 0] > self.minpc0[None]
        # inside *= iarray[:, 0] < self.maxpc0[None]
        # inside *= iarray[:, 1] > self.minpc1[None]
        # inside *= iarray[:, 1] < self.maxpc1[None]
        # inside *= iarray[:, 2] > self.minpc2[None]
        # inside *= iarray[:, 2] < self.maxpc2[None]

        return ee, inside

    def evaluate_value(self, array, prop, region='everywhere'):
        return self.eval_interpolant(array, prop, region)

    def evaluate_gradient(self, array, prop, region='everywhere'):
        return self.eval_gradient(array, prop, region)

    def eval_interpolant(self, array, prop, k=5, e=None, region='everywhere'):
        """
        Evaluate an interpolant from property on an array of points.
        Uses numpy to speed up calculations but could be expensive for large
        mesh/points
        """
        if e == None:
            e, inside = self.elements_for_array(array, k)
        else:
            inside = np.array(e.shape).astype(bool)
            inside[:] = True

        bc = self.calc_bary_c(e[inside], array[inside])
        prop_int = np.zeros(e.shape)
        nv = np.zeros(self.properties[prop].shape)
        nv[~self.regions[region]] = np.nan
        nv[self.regions[region]] = self.properties[prop][self.regions[region]]
        props = self.properties[prop][self.elements[e[inside]]]
        prop_int[inside] = np.sum((bc.T * props), axis=1)
        prop_int[~inside] = np.nan
        return prop_int

    def element_property_value(self, prop):
        """
        Gets the average property value for all of the elements
        :param prop:
        :return:
        """
        bc = np.zeros(4)
        bc[:] = 0.25
        e = np.arange(self.n_elements)
        prop_int = np.zeros(e.shape)

        props = self.properties[prop][self.elements[e]]
        prop_int = np.sum((bc.T * props), axis=1)
        return prop_int

    def element_property_gradient(self, prop):
        """
        Get the gradient of a property for all elements in the mesh
        :param prop:
        :return:
        """
        e = np.arange(self.n_elements)

        grads = self.element_gradients[e]
        vals = self.properties[prop][self.elements[e]]
        # grads = np.swapaxes(grads,1,2)
        a = np.zeros((self.n_elements, 3))  # array.shape)
        a = (grads * vals[:, None, :]).sum(2) / 4.  # @ vals.T/
        a /= np.sum(a, axis=1)[:, None]
        return a

    def eval_gradient(self, array, prop, k=5, region='everywhere'):
        """
        Evaluate an interpolant from property on an array of points.
        Uses numpy to speed up calculations but could be expensive for large
        mesh/points
        """
        e, inside = self.elements_for_array(array, k)
        # ps = self.nodes[self.elements[e[inside]]]
        # m = np.array(
        #     [[(ps[:, 1, 0] - ps[:, 0, 0]), (ps[:, 1, 1] - ps[:, 0, 1]),
        #     (ps[:, 1, 2] - ps[:, 0, 2])],
        #      [(ps[:, 2, 0] - ps[:, 0, 0]), (ps[:, 2, 1] - ps[:, 0, 1]),
        #      (ps[:, 2, 2] - ps[:, 0, 2])],
        #      [(ps[:, 3, 0] - ps[:, 0, 0]), (ps[:, 3, 1] - ps[:, 0, 1]),
        #      (ps[:, 3, 2] - ps[:, 0, 2])]])
        # I = np.array(
        #     [[-1., 1., 0., 0.],
        #      [-1., 0., 1., 0.],
        #      [-1., 0., 0., 1.]])
        # m = np.swapaxes(m, 0, 2)
        # grads = la.inv(m)
        #
        # grads = grads.swapaxes(1, 2)
        # grads = grads @ I
        grads = self.element_gradients[e]
        nv = np.zeros(self.properties[prop].shape)
        nv[~self.regions[region]] = np.nan
        nv[self.regions[region]] = self.properties[prop][self.regions[region]]
        vals = self.properties[prop][self.elements[e[inside]]]
        a = np.zeros(array.shape)
        a[inside] = (grads * vals[:, None, :]).sum(2) / 4.  # @ vals.T/
        a[~inside, :] = np.nan
        asum = np.zeros(a.shape[0])
        asum[inside] = np.sum(a[inside, :], axis=1)
        inside = ~np.isnan(asum)
        logic = np.zeros(asum.shape).astype(bool)
        logic[:] = False
        logic[inside] = asum[inside] > 0
        a[logic] /= asum[logic, None]
        return a



    def slice(self, propertyname, isovalue, region='everywhere'):
        """
        Create a triangular surface from an isovalue of the scalar field
        Parameters
        ----------
        isovalue - value for creating surface for

        Returns
        -------

        """
        logger.error("function has been removed, please use the modelviewer class")
        return



In [299]:
%%cython -a
import numpy as np
def build_aabb(int nx, int ny, int nz, long [:,:] tetra, double [:,:] nodes, long [:,:] aabb, double [:] step):
    cdef int i, ntetra, j, ix, iy, iz
    cdef double [:,:] bb = np.zeros((2,3))
#     cdef double [:] maxs = np.zeros(3)
    cdef double [:,:] points = np.zeros((4,3))
    ntetra = tetra.shape[0]
    # create a mask for extracting corners from 
    cdef long [:,:] corners = np.array([[0, 1, 0, 0, 1, 0, 1, 1],
                                      [0, 0, 1, 0, 0, 1, 1, 1],
                                      [0, 0, 0, 1, 1, 1, 0, 1]]).astype(int)
    for i in range(ntetra):
        # copy points into tmp array
        for k in range(4):
            for l in range(3):
                points[k,l] = nodes[tetra[i,k],l]
        for l in range(3):
            bb[0,l] = np.min(points[:,l])#,axis=0)
            bb[1,l] = np.max(points[:,l])#,axis=0)
        
        for j in range(8):
            ix = int(bb[corners[0,j],0] // step[0])
            iy = int(bb[corners[1,j],1] // step[1])
            iz = int(bb[corners[2,j],2] // step[2])
#         print(ix,iy,iz)
            aabb[ix+nx*iy+nx*ny*iz,i] = i
        
    return

In [ ]:
# %%cython -a
# def find_tetras(double [:,:] nodes, long [:,:] tetras, long [:,:] aabbindx, double [:,:] pos):
#     cdef npts = pos.shape[0]
#     cdef i,j,k
#     for i in range(npts):
#         vap = pos[i,:] - nodes[] 
#     vap = pos[:,None,:] - points[:, :, 0, :]
#         vbp = pos[:,None,:] - points[:, :, 1, :]
#         # vcp = p - points[:, 2, :]
#         # vdp = p - points[:, 3, :]
#         vab = points[:, :, 1, :] - points[:, :, 0, :]
#         vac = points[:, :, 2, :] - points[:, :, 0, :]
#         vad = points[:, :, 3, :] - points[:, :, 0, :]
#         vbc = points[:, :, 2, :] - points[:, :, 1, :]
#         vbd = points[:, :, 3, :] - points[:, :, 1, :]
        
#         va = np.einsum('ikj, iklj->ikl', vbp, np.cross(vbd, vbc, axisa=2, axisb=2)) / 6.
#         vb = np.einsum('ikj, iklj->ikl', vap, np.cross(vac, vad, axisa=2, axisb=2)) / 6.
#         vc = np.einsum('ikj, iklj->ikl', vap, np.cross(vad, vab, axisa=2, axisb=2)) / 6.
#         vd = np.einsum('ikj, iklj->ikl', vap, np.cross(vab, vac, axisa=2, axisb=2)) / 6.
#         v = np.einsum('ikj, iklj->ikl', vab, np.cross(vac, vad, axisa=2, axisb=2)) / 6.
#         c = np.zeros((va.shape[0],va.shape[1],4))

In [341]:
class TetMesh2:
    def __init__(self,origin,maximum,nodes,tetra,neighbours,nx=5,ny=5,nz=5):
        self.origin = np.array(origin)
        self.maximum = np.array(maximum)
        self.nodes = nodes
        self.tetra = tetra
        self.ntetra = tetra.shape[0]

        self.neighbours = neighbours
        self.step = (self.maximum-self.origin)/(np.array([nx,ny,nz])-1)
        self.aabb = np.zeros((nx*ny*nz,self.ntetra)).astype(int)
        self.aabb[:] = -1
        self.nx = nx
        self.nz = nz
        self.ny = ny
        self._build_aabb()
        self.corners = np.array([[0, 1, 0, 0, 1, 0, 1, 1],
                                      [0, 0, 1, 0, 0, 1, 1, 1],
                                      [0, 0, 0, 1, 1, 1, 0, 1]]).astype(int)
    def _build_aabb(self):
        build_aabb(self.nx,self.ny,self.nz,self.tetra,self.nodes-self.origin,self.aabb,self.step)
        # now sort
    def get_tetra(self,pos):
        pos = np.array(pos)
        tetras = np.zeros(pos.shape[0]).astype(int)
        bcs = np.zeros((pos.shape[0],4))
        for i in range(pos.shape[0]):
            aabbidx = self.pos_to_aabb_index(pos)
            print(aabbidx)
            cells = self.aabb[aabbidx[i],:]
            cells=cells[cells>=0]
            npts = len(cells)
            points = self.nodes[self.tetra[cells]]
            vap = pos[i,:] - points[:, 0, :]
            vbp = pos[i,:] - points[:, 1, :]
            # vcp = p - points[:, 2, :]
            # vdp = p - points[:, 3, :]
            vab = points[:, 1, :] - points[:, 0, :]
            vac = points[:, 2, :] - points[:, 0, :]
            vad = points[:, 3, :] - points[:, 0, :]
            vbc = points[:, 2, :] - points[:, 1, :]
            vbd = points[:, 3, :] - points[:, 1, :]

            va = np.sum(vbp * np.cross(vbd, vbc, axisa=1, axisb=1), axis=1) / 6.
            vb = np.sum(vap * np.cross(vac, vad, axisa=1, axisb=1), axis=1) / 6.
            vc = np.sum(vap * np.cross(vad, vab, axisa=1, axisb=1), axis=1) / 6.
            vd = np.sum(vap * np.cross(vab, vac, axisa=1, axisb=1), axis=1) / 6.
            v = np.sum(vab * np.cross(vac, vad, axisa=1, axisb=1), axis=1) / 6.
            
            c = np.zeros((4, npts))
            c[0, :] = va / v
            c[1, :] = vb / v
            c[2, :] = vc / v
            c[3, :] = vd / v
            tetras[i] = cells[np.all(c>0,axis=0)]
            #             print(c)
            bcs[i,:] = c[:,np.all(c>0,axis=0)].T
        return tetras,bcs
#         return self.aabb[aabbidx,:]
    def pos_to_aabb_index(self,pos):
        ix = pos[:, 0] - self.origin[None, 0]
        iy = pos[:, 1] - self.origin[None, 1]
        iz = pos[:, 2] - self.origin[None, 2]
        ix = ix // self.step[None, 0]
        iy = iy // self.step[None, 1]
        iz = iz // self.step[None, 2]
        return ix.astype(int)+iy.astype(int)*self.nx+iz.astype(int)*self.nx*self.ny
    
    def aabb_index_to_pos(self,global_index):
        global_index = np.array(global_index)
        x_index = global_index % self.nx
        y_index = global_index // self.nx % \
                  self.ny
        z_index = global_index // self.nx // \
                  self.ny
        xcorner = np.array([0, 1, 0, 0, 1, 0, 1, 1])
        ycorner = np.array([0, 0, 1, 0, 0, 1, 1, 1])
        zcorner = np.array([0, 0, 0, 1, 1, 1, 0, 1])
        xcorners = x_index[:, None] + xcorner[None, :]
        ycorners = y_index[:, None] + ycorner[None, :]
        zcorners = z_index[:, None] + zcorner[None, :]
        corner_pos = self.origin[:,None]+self.step[:,None]*np.vstack([xcorners,ycorners,zcorners])
        print(corner_pos)

In [342]:
mesh = build([0,-.9,0],[1,1,1],1000)

In [343]:
mesh.aabb_index_to_pos([62])

[[0.5   0.75  0.5   0.5   0.75  0.5   0.75  0.75 ]
 [0.05  0.05  0.525 0.05  0.05  0.525 0.525 0.525]
 [0.5   0.5   0.5   0.75  0.75  0.75  0.5   0.75 ]]


In [344]:
mesh.get_tetra(np.array([[0.69,0.5,.99]]))#np.random.random((100,3)))
# for i in range(100):
#     print(A[i,A[i,:]>0])

[87]


ValueError: setting an array element with a sequence.

In [167]:
for i in range(mesh.nx*mesh.ny*mesh.nz):
    tetra = mesh.aabb[i,mesh.aabb[i,:]>0]
    print(tetra)

[  17   58  100  206  341  441  447  460  482  601  610  833  837  855
  856  857  858  936 1025 1158 1361]
[ 302  415  587  613  621  728  771  820  821  827  859  883  913  922
 1233]
[  84   99  161  210  535  558  757  758  760  887 1111 1219 1223 1229]
[ 71 397 442 563 591 642 761 909 910 911 912]
[ 79 136 246 295 412 467 568 582 597 605 606 669 682 748 867]
[  87  113  236  239  349  391  396  452  532  557  602 1262 1354 1363
 1374]
[ 256  283  834  868  886 1029 1212 1231 1243 1362 1391]
[ 123  155  423  559  572 1073 1077 1154 1464 1469 1470]
[  31  517  619  640  765  846  863 1131 1376 1378 1379]
[  45  273  504  617  618  690  764  822  824  891 1011 1042 1095]
[189 221 292 542 691 694 840]
[  51   83  199  525 1190 1382 1385 1386 1387 1390]
[  80  304  346  483  740  971 1002 1003 1146 1153 1167 1195 1234 1236]
[ 335  598 1004 1086 1377 1423]
[ 122  169  244  257  312  313  574  739  742  823  835  966 1070]
[  30   33   95  203  310  315  569  655  661  755 1443 1444 1449

In [111]:
for i

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [36]:
np.max(np.random.random((4,3)),axis=0)

array([0.84214008, 0.89793046, 0.80237811])

In [29]:
10.3//10

1.0

In [30]:
corners = np.array([[0, 1, 0, 0, 1, 0, 1, 1],
                                      [0, 0, 1, 0, 0, 1, 1, 1],
                                      [0, 0, 0, 1, 1, 1, 0, 1]]) 

In [31]:
corners[0,:]

array([0, 1, 0, 0, 1, 0, 1, 1])

In [43]:
def build(origin,maximum,n_tetra):
    minx = origin[0]
    miny = origin[1]
    minz = origin[2]
    maxx = maximum[0]
    maxy =  maximum[1]
    maxz =  maximum[2]
    points = np.array([
        (minx, miny, minz),
        (maxx, miny, minz),
        (maxx, maxy, minz),
        (minx, maxy, minz),
        (minx, miny, maxz),
        (maxx, miny, maxz),
        (maxx, maxy, maxz),
        (minx, maxy, maxz)
    ])
#         self.surfaces['top'] = (
#             (minx, miny, maxz), (maxx, miny, maxz), (maxx, maxy, maxz),
#             (minx, maxy, maxz))
#         self.surfaces['bottom'] = (
#             (minx, miny, minz), (maxx, miny, minz), (maxx, maxy, minz),
#             (minx, maxy, minz))

#         self.points = points
#         # calculate the 3 principal components to find the local coordinate
#         # system
#         self.pca.fit(points)
#         # project the points into this coordinate system
#         newp = self.pca.transform(points)

    lengthU = maxx - minx
    lengthV = maxy - miny
    lengthW = maxz - minz
    boxVol = lengthU * lengthW * lengthV
    correction_factor = 1.91
    maxvol = correction_factor * boxVol / n_tetra
    facets = [
        [0, 1, 2, 3],
        [4, 5, 6, 7],
        [0, 4, 5, 1],
        [1, 5, 6, 2],
        [2, 6, 7, 3],
        [3, 7, 4, 0]
    ]

    # create the mesh
    info = meshpy.tet.MeshInfo()
    # use the projected points to build the mesh
    info.set_points(points)
    info.set_facets(facets)
    meshpy_mesh = meshpy.tet.build(info, max_volume=maxvol,
                                   options=meshpy.tet.Options('pqn'))
    nodes = np.array(meshpy_mesh.points)
    elements=  np.array(meshpy_mesh.elements, dtype=np.int64)
    neighbours = np.array(meshpy_mesh.neighbors, dtype=np.int64)
    return TetMesh2(origin,maximum,nodes,elements,neighbours)#    def __init__(self,origin,maximum,nodes,tetra,neighbours,nx=10,ny=10,nz=10):
