In [1]:
from LoopStructural.supports.structured_tetra import TetMesh
from LoopStructural.cython.dsi_helper import tetra_neighbours
import numpy as np

/home/lgrose/anaconda3/envs/loop/lib/python3.8/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.decomposition.pca module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.decomposition. Anything that cannot be imported from sklearn.decomposition is now part of the private API.
  warnings.warn(message, FutureWarning)


In [2]:
mesh = TetMesh(nsteps=[2,2,2])
mesh.nodes

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 1., 0.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [1., 1., 1.]])

In [3]:
mesh = TetMesh(nsteps=[2,3,3])
neighbours = np.sort(mesh.get_neighbours())[:,::-1]
elements = mesh.get_elements()
neighbours2 = np.zeros((elements.shape[0],4)).astype('int64')
neighbours2[:] = -1
tetra_neighbours(elements,neighbours2)
neighbours2 = np.sort(neighbours2)[:,::-1]
print(neighbours)
print(neighbours2)
for i in range(neighbours2.shape[0]):
    for j in range(4):
        if neighbours[i,j] not in neighbours2[i,:]:
            print(i,i % 5, (i // 5) % 2, mesh.global_index_to_cell_index(i//5)[0],\
                  mesh.global_index_to_cell_index(i//5)[1],\
                  mesh.global_index_to_cell_index(i//5)[2],neighbours[i,:],neighbours2[i,:])

[[ 4  3  2  1]
 [13  7  0 -1]
 [14  0 -1 -1]
 [ 0 -1 -1 -1]
 [ 9  0 -1 -1]
 [ 9  8  7  6]
 [19  5 -1 -1]
 [18  5  1 -1]
 [ 5 -1 -1 -1]
 [ 5  4 -1 -1]
 [14 13 12 11]
 [17 10 -1 -1]
 [10 -1 -1 -1]
 [18 10  1 -1]
 [10  2 -1 -1]
 [19 18 17 16]
 [15 -1 -1 -1]
 [15 11 -1 -1]
 [15 13  7 -1]
 [15  6 -1 -1]]
[[ 4  3  2  1]
 [13  7  0 -1]
 [14  0 -1 -1]
 [ 0 -1 -1 -1]
 [ 9  0 -1 -1]
 [ 9  8  7  6]
 [19  5 -1 -1]
 [18  5  1 -1]
 [ 5 -1 -1 -1]
 [ 5  4 -1 -1]
 [14 13 12 11]
 [17 10 -1 -1]
 [10 -1 -1 -1]
 [18 10  1 -1]
 [10  2 -1 -1]
 [19 18 17 16]
 [15 -1 -1 -1]
 [15 11 -1 -1]
 [15 13  7 -1]
 [15  6 -1 -1]]


In [4]:
mesh = TetMesh(nsteps=[2,3,2])
neighbours = np.sort(mesh.get_neighbours())[:,::-1]
elements = mesh.get_elements()
neighbours2 = np.zeros((elements.shape[0],4)).astype('int64')
neighbours2[:] = -1
tetra_neighbours(elements,neighbours2)
neighbours2 = np.sort(neighbours2)[:,::-1]
for i in range(neighbours2.shape[0]):
    for j in range(4):
        if neighbours[i,j] not in neighbours2[i,:]:
            print(i,i % 5, (i // 5) % 2, mesh.global_index_to_cell_index(i//5)[0],\
                  mesh.global_index_to_cell_index(i//5)[1],\
                  mesh.global_index_to_cell_index(i//5)[2],neighbours[i,:],neighbours2[i,:])

In [5]:
mesh = TetMesh(nsteps=[2,2,3])
neighbours = np.sort(mesh.get_neighbours())[:,::-1]
elements = mesh.get_elements()
neighbours2 = np.zeros((elements.shape[0],4)).astype('int64')
neighbours2[:] = -1
tetra_neighbours(elements,neighbours2)
neighbours2 = np.sort(neighbours2)[:,::-1]

for i in range(neighbours2.shape[0]):
    for j in range(4):
        if neighbours[i,j] not in neighbours2[i,:]:
            print(i,i % 5, (i // 5) % 2, mesh.global_index_to_cell_index(i//5)[0],\
                  mesh.global_index_to_cell_index(i//5)[1],\
                  mesh.global_index_to_cell_index(i//5)[2],neighbours[i,:],neighbours2[i,:])

In [11]:
mesh = TetMesh(nsteps=[30,30,30])


In [12]:
ic = 24 // 5
it = 24 % 5
print(mesh.global_index_to_cell_index(ic),it)

(array([4]), array([0]), array([0])) 4


In [13]:

# get cell corners
xi, yi, zi = mesh.cell_corner_indexes(c_xi, c_yi, c_zi)
even_mask = (c_xi + c_yi + c_zi) % 2 == 0
gi = xi + yi * mesh.nsteps[0] + zi * mesh.nsteps[0] * mesh.nsteps[1]
tetras = np.zeros((c_xi.shape[0], 5, 4)).astype('int64')
tetras[even_mask, :, :] = gi[even_mask, :][:, mesh.tetra_mask_even]
tetras[~even_mask, :, :] = gi[~even_mask, :][:, mesh.tetra_mask]
tetras = tetras.reshape((tetras.shape[0]*tetras.shape[1],tetras.shape[2]))

In [14]:
tetras

array([[  931,     1,    30,   900],
       [  930,    30,   900,   931],
       [  901,     1,   900,   931],
       ...,
       [26969, 26069, 26968, 26999],
       [26068, 26069, 26098, 26968],
       [26099, 26069, 26098, 26999]])

In [15]:
elements = mesh.get_elements()

In [16]:
print(tetras-elements)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 ...
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
