In [1]:
import numpy as np

In [8]:
a = np.arange(12)
print(a)
a = a.reshape((3,2,2))
print(a)

a.reshape((3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
a.ndims()

AttributeError: 'numpy.ndarray' object has no attribute 'ndims'